// Generated by Thrift2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: cassandra.thrift
// cassandra.thrift: namespace java org.apache.cassandra.thrift
// cassandra.thrift: namespace cpp org.apache.cassandra
// cassandra.thrift: namespace csharp Apache.Cassandra
// cassandra.thrift: namespace py cassandra
// cassandra.thrift: namespace php cassandra
// cassandra.thrift: namespace perl Cassandra
// cassandra.thrift: namespace rb CassandraThrift
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.thrift {
    /**
        <see cref = 'AuthenticationException'/>
        <see cref = 'AuthenticationRequest'/>
        <see cref = 'AuthorizationException'/>
        <see cref = 'CASResult'/>
        <see cref = 'Cassandra_add_Args'/>
        <see cref = 'Cassandra_add_Result'/>
        <see cref = 'Cassandra_atomic_batch_mutate_Args'/>
        <see cref = 'Cassandra_atomic_batch_mutate_Result'/>
        <see cref = 'Cassandra_batch_mutate_Args'/>
        <see cref = 'Cassandra_batch_mutate_Result'/>
        <see cref = 'Cassandra_cas_Args'/>
        <see cref = 'Cassandra_cas_Result'/>
        <see cref = 'Cassandra_describe_cluster_name_Args'/>
        <see cref = 'Cassandra_describe_cluster_name_Result'/>
        <see cref = 'Cassandra_describe_keyspace_Args'/>
        <see cref = 'Cassandra_describe_keyspace_Result'/>
        <see cref = 'Cassandra_describe_keyspaces_Args'/>
        <see cref = 'Cassandra_describe_keyspaces_Result'/>
        <see cref = 'Cassandra_describe_local_ring_Args'/>
        <see cref = 'Cassandra_describe_local_ring_Result'/>
        <see cref = 'Cassandra_describe_partitioner_Args'/>
        <see cref = 'Cassandra_describe_partitioner_Result'/>
        <see cref = 'Cassandra_describe_ring_Args'/>
        <see cref = 'Cassandra_describe_ring_Result'/>
        <see cref = 'Cassandra_describe_schema_versions_Args'/>
        <see cref = 'Cassandra_describe_schema_versions_Result'/>
        <see cref = 'Cassandra_describe_snitch_Args'/>
        <see cref = 'Cassandra_describe_snitch_Result'/>
        <see cref = 'Cassandra_describe_splits_Args'/>
        <see cref = 'Cassandra_describe_splits_Result'/>
        <see cref = 'Cassandra_describe_splits_ex_Args'/>
        <see cref = 'Cassandra_describe_splits_ex_Result'/>
        <see cref = 'Cassandra_describe_token_map_Args'/>
        <see cref = 'Cassandra_describe_token_map_Result'/>
        <see cref = 'Cassandra_describe_version_Args'/>
        <see cref = 'Cassandra_describe_version_Result'/>
        <see cref = 'Cassandra_execute_cql3_query_Args'/>
        <see cref = 'Cassandra_execute_cql3_query_Result'/>
        <see cref = 'Cassandra_execute_cql_query_Args'/>
        <see cref = 'Cassandra_execute_cql_query_Result'/>
        <see cref = 'Cassandra_execute_prepared_cql3_query_Args'/>
        <see cref = 'Cassandra_execute_prepared_cql3_query_Result'/>
        <see cref = 'Cassandra_execute_prepared_cql_query_Args'/>
        <see cref = 'Cassandra_execute_prepared_cql_query_Result'/>
        <see cref = 'Cassandra_get_Args'/>
        <see cref = 'Cassandra_get_Result'/>
        <see cref = 'Cassandra_get_count_Args'/>
        <see cref = 'Cassandra_get_count_Result'/>
        <see cref = 'Cassandra_get_indexed_slices_Args'/>
        <see cref = 'Cassandra_get_indexed_slices_Result'/>
        <see cref = 'Cassandra_get_multi_slice_Args'/>
        <see cref = 'Cassandra_get_multi_slice_Result'/>
        <see cref = 'Cassandra_get_paged_slice_Args'/>
        <see cref = 'Cassandra_get_paged_slice_Result'/>
        <see cref = 'Cassandra_get_range_slices_Args'/>
        <see cref = 'Cassandra_get_range_slices_Result'/>
        <see cref = 'Cassandra_get_slice_Args'/>
        <see cref = 'Cassandra_get_slice_Result'/>
        <see cref = 'Cassandra_insert_Args'/>
        <see cref = 'Cassandra_insert_Result'/>
        <see cref = 'Cassandra_login_Args'/>
        <see cref = 'Cassandra_login_Result'/>
        <see cref = 'Cassandra_multiget_count_Args'/>
        <see cref = 'Cassandra_multiget_count_Result'/>
        <see cref = 'Cassandra_multiget_slice_Args'/>
        <see cref = 'Cassandra_multiget_slice_Result'/>
        <see cref = 'Cassandra_prepare_cql3_query_Args'/>
        <see cref = 'Cassandra_prepare_cql3_query_Result'/>
        <see cref = 'Cassandra_prepare_cql_query_Args'/>
        <see cref = 'Cassandra_prepare_cql_query_Result'/>
        <see cref = 'Cassandra_remove_Args'/>
        <see cref = 'Cassandra_remove_Result'/>
        <see cref = 'Cassandra_remove_counter_Args'/>
        <see cref = 'Cassandra_remove_counter_Result'/>
        <see cref = 'Cassandra_set_cql_version_Args'/>
        <see cref = 'Cassandra_set_cql_version_Result'/>
        <see cref = 'Cassandra_set_keyspace_Args'/>
        <see cref = 'Cassandra_set_keyspace_Result'/>
        <see cref = 'Cassandra_system_add_column_family_Args'/>
        <see cref = 'Cassandra_system_add_column_family_Result'/>
        <see cref = 'Cassandra_system_add_keyspace_Args'/>
        <see cref = 'Cassandra_system_add_keyspace_Result'/>
        <see cref = 'Cassandra_system_drop_column_family_Args'/>
        <see cref = 'Cassandra_system_drop_column_family_Result'/>
        <see cref = 'Cassandra_system_drop_keyspace_Args'/>
        <see cref = 'Cassandra_system_drop_keyspace_Result'/>
        <see cref = 'Cassandra_system_update_column_family_Args'/>
        <see cref = 'Cassandra_system_update_column_family_Result'/>
        <see cref = 'Cassandra_system_update_keyspace_Args'/>
        <see cref = 'Cassandra_system_update_keyspace_Result'/>
        <see cref = 'Cassandra_trace_next_query_Args'/>
        <see cref = 'Cassandra_trace_next_query_Result'/>
        <see cref = 'Cassandra_truncate_Args'/>
        <see cref = 'Cassandra_truncate_Result'/>
        <see cref = 'CfDef'/>
        <see cref = 'CfSplit'/>
        <see cref = 'Column'/>
        <see cref = 'ColumnDef'/>
        <see cref = 'ColumnOrSuperColumn'/>
        <see cref = 'ColumnParent'/>
        <see cref = 'ColumnPath'/>
        <see cref = 'ColumnSlice'/>
        <see cref = 'CounterColumn'/>
        <see cref = 'CounterSuperColumn'/>
        <see cref = 'CqlMetadata'/>
        <see cref = 'CqlPreparedResult'/>
        <see cref = 'CqlResult'/>
        <see cref = 'CqlRow'/>
        <see cref = 'Deletion'/>
        <see cref = 'EndpointDetails'/>
        <see cref = 'IndexClause'/>
        <see cref = 'IndexExpression'/>
        <see cref = 'InvalidRequestException'/>
        <see cref = 'KeyCount'/>
        <see cref = 'KeyRange'/>
        <see cref = 'KeySlice'/>
        <see cref = 'KsDef'/>
        <see cref = 'MultiSliceRequest'/>
        <see cref = 'Mutation'/>
        <see cref = 'NotFoundException'/>
        <see cref = 'SchemaDisagreementException'/>
        <see cref = 'SlicePredicate'/>
        <see cref = 'SliceRange'/>
        <see cref = 'SuperColumn'/>
        <see cref = 'TimedOutException'/>
        <see cref = 'TokenRange'/>
        <see cref = 'TriggerDef'/>
        <see cref = 'UnavailableException'/>
        <see cref = 'Wrap_Map_string_to_List_Mutation'/>
    */
    public interface cassandra {
        // A trailing `// N:` on a field is its Thrift field id; `<field>_default` is the field's Thrift default.
        // Neither is read by AdHoc.
        // Thrift declares no size bounds. These permissive defaults replace AdHoc's 255 limit;
        // add [D(+N)] on a field whose real bound is known.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        // ═════════════════════════ cassandra.thrift ═════════════════════════

        /** Thrift `const` declarations of cassandra.thrift (non-transmittable constants container). */
        public struct Consts {
            /**
            The API version (NOT the product version), composed as a dot delimited
            string with major, minor, and patch level components.
            - Major: Incremented for backward incompatible changes. An example would
            be changes to the number or disposition of method arguments.
            - Minor: Incremented for backward compatible changes. An example would
            be the addition of a new (optional) method.
            - Patch: Incremented for bug fixes. The patch level should be increased
            for every edit that doesn't result in a change to major/minor.
            See the Semantic Versioning Specification (SemVer) http://semver.org.
            Note that this backwards compatibility is from the perspective of the server,
            not the client. Cassandra should always be able to talk to older client
            software, but client software may not be able to talk to older Cassandra
            instances.
            An effort should be made not to break forward-client-compatibility either
            (e.g. one should avoid removing obsolete fields from the IDL), but no
            guarantees in this respect are made by the Cassandra project.
            */
            public const string VERSION = "20.1.0";
        }

        /**
        service api
        The ConsistencyLevel is an enum that controls both read and write
        behavior based on the ReplicationFactor of the keyspace.  The
        different consistency levels have different meanings, depending on
        if you're doing a write or read operation.
        If W + R &gt; ReplicationFactor, where W is the number of nodes to
        block for on write, and R the number to block for on reads, you
        will have strongly consistent behavior; that is, readers will
        always see the most recent write. Of these, the most interesting is
        to do QUORUM reads and writes, which gives you consistency while
        still allowing availability in the face of node failures up to half
        of &lt;ReplicationFactor&gt;. Of course if latency is more important than
        consistency then you can use lower values for either or both.
        Some ConsistencyLevels (ONE, TWO, THREE) refer to a specific number
        of replicas rather than a logical concept that adjusts
        automatically with the replication factor.  Of these, only ONE is
        commonly used; TWO and (even more rarely) THREE are only useful
        when you care more about guaranteeing a certain level of
        durability, than consistency.
        Write consistency levels make the following guarantees before reporting success to the client:
        ANY          Ensure that the write has been written once somewhere, including possibly being hinted in a
        non-target node.
        ONE          Ensure that the write has been written to at least 1 node's commit log and memory table
        TWO          Ensure that the write has been written to at least 2 node's commit log and memory table
        THREE        Ensure that the write has been written to at least 3 node's commit log and memory table
        QUORUM       Ensure that the write has been written to &lt;ReplicationFactor&gt; / 2 + 1 nodes
        LOCAL_ONE    Ensure that the write has been written to 1 node within the local datacenter (requires
        NetworkTopologyStrategy)
        LOCAL_QUORUM Ensure that the write has been written to &lt;ReplicationFactor&gt; / 2 + 1 nodes, within the
        local datacenter (requires NetworkTopologyStrategy)
        EACH_QUORUM  Ensure that the write has been written to &lt;ReplicationFactor&gt; / 2 + 1 nodes in each
        datacenter (requires NetworkTopologyStrategy)
        ALL          Ensure that the write is written to &lt;code&gt;&amp;lt;ReplicationFactor&amp;gt;&lt;/code&gt;
        nodes before responding to the client.
        Read consistency levels make the following guarantees before returning successful results to the client:
        ANY          Not supported. You probably want ONE instead.
        ONE          Returns the record obtained from a single replica.
        TWO          Returns the record with the most recent timestamp once two replicas have replied.
        THREE        Returns the record with the most recent timestamp once three replicas have replied.
        QUORUM       Returns the record with the most recent timestamp once a majority of replicas have replied.
        LOCAL_ONE    Returns the record with the most recent timestamp once a single replica within the local
        datacenter have replied.
        LOCAL_QUORUM Returns the record with the most recent timestamp once a majority of replicas within the local
        datacenter have replied.
        EACH_QUORUM  Returns the record with the most recent timestamp once a majority of replicas within each
        datacenter have replied.
        ALL          Returns the record with the most recent timestamp once all replicas have replied (implies no
        replica may be down)..
        */
        enum ConsistencyLevel {
            ONE = 1,
            QUORUM = 2,
            LOCAL_QUORUM = 3,
            EACH_QUORUM = 4,
            ALL = 5,
            ANY = 6,
            TWO = 7,
            THREE = 8,
            SERIAL = 9,
            LOCAL_SERIAL = 10,
            LOCAL_ONE = 11,
        }

        enum IndexOperator {
            EQ = 0,
            GTE = 1,
            GT = 2,
            LTE = 3,
            LT = 4,
        }

        enum IndexType {
            KEYS = 0,
            CUSTOM = 1,
            COMPOSITES = 2,
        }

        /**
        CQL query compression
        */
        enum Compression {
            GZIP = 1,
            NONE = 2,
        }

        enum CqlResultType {
            ROWS = 1,
            VOID = 2,
            INT = 3,
        }

        /**
        data structures
        Basic unit of data within a ColumnFamily.
        @param name, the name by which this column is set and retrieved.  Maximum 64KB long.
        @param value. The data associated with the name.  Maximum 2GB long, but in practice you should limit it to
        small numbers of MB (since Thrift must read the full value into memory to operate on it).
        @param timestamp. The timestamp is used for conflict detection/resolution when two columns with same name need
        to be compared.
        @param ttl. An optional, positive delay (in seconds) after which the column will be automatically deleted.
        */
        public class Column {
            Binary[,,] name; // 1:
            Binary[,,] value; // 2:
            [X] long? timestamp; // 3:
            [X] int? ttl; // 4:
        }

        /**
        A named list of columns.
        @param name. see Column.name.
        @param columns. A collection of standard Columns.  The columns within a super column are defined in an adhoc
        manner.
        Columns within a super column do not have to have matching structures (similarly named child columns).
        */
        public class SuperColumn {
            Binary[,,] name; // 1:
            Column[,,] columns; // 2:
        }

        public class CounterColumn {
            Binary[,,] name; // 1:
            [X] long value; // 2:
        }

        public class CounterSuperColumn {
            Binary[,,] name; // 1:
            CounterColumn[,,] columns; // 2:
        }

        /**
        Methods for fetching rows/records from Cassandra will return either a single instance of ColumnOrSuperColumn
        or a list
        of ColumnOrSuperColumns (get_slice()). If you're looking up a SuperColumn (or list of SuperColumns) then the
        resulting
        instances of ColumnOrSuperColumn will have the requested SuperColumn in the attribute super_column. For
        queries resulting
        in Columns, those values will be in the attribute column. This change was made between 0.3 and 0.4 to
        standardize on
        single query methods that may return either a SuperColumn or Column.
        If the query was on a counter column family, you will either get a counter_column (instead of a column) or a
        counter_super_column (instead of a super_column)
        @param column. The Column returned by get() or get_slice().
        @param super_column. The SuperColumn returned by get() or get_slice().
        @param counter_column. The Counterolumn returned by get() or get_slice().
        @param counter_super_column. The CounterSuperColumn returned by get() or get_slice().
        */
        public class ColumnOrSuperColumn {
            Column column; // 1:
            SuperColumn super_column; // 2:
            CounterColumn counter_column; // 3:
            CounterSuperColumn counter_super_column; // 4:
        }

        /**
        Exceptions
        (note that internal server errors will raise a TApplicationException, courtesy of Thrift)
        A specific column was requested that does not exist.
        Thrift exception.
        */
        public class NotFoundException {
        }

        /**
        Invalid request could mean keyspace or column family does not exist, required parameters are missing, or a
        parameter is malformed.
        why contains an associated error message.
        Thrift exception.
        */
        public class InvalidRequestException {
            string why; // 1:
        }

        /**
        Not all the replicas required could be created and/or read.
        Thrift exception.
        */
        public class UnavailableException {
        }

        /**
        RPC timeout was exceeded.  either a node failed mid-operation, or load was too high, or the requested op was
        too large.
        Thrift exception.
        */
        public class TimedOutException {
            /**
            if a write operation was acknowledged by some replicas but not by enough to
            satisfy the required ConsistencyLevel, the number of successful
            replies will be given here. In case of atomic_batch_mutate method this field
            will be set to -1 if the batch was written to the batchlog and to 0 if it wasn't.
            */
            [X] int? acknowledged_by; // 1:
            /**
            in case of atomic_batch_mutate method this field tells if the batch
            was written to the batchlog.
            */
            bool? acknowledged_by_batchlog; // 2:
            /**
            for the CAS method, this field tells if we timed out during the paxos
            protocol, as opposed to during the commit of our update
            */
            bool? paxos_in_progress; // 3:
        }

        /**
        invalid authentication request (invalid keyspace, user does not exist, or credentials invalid)
        Thrift exception.
        */
        public class AuthenticationException {
            string why; // 1:
        }

        /**
        invalid authorization request (user does not have access to keyspace)
        Thrift exception.
        */
        public class AuthorizationException {
            string why; // 1:
        }

        /**
        NOTE: This up outdated exception left for backward compatibility reasons,
        no actual schema agreement validation is done starting from Cassandra 1.2
        schemas are not in agreement across all nodes
        Thrift exception.
        */
        public class SchemaDisagreementException {
        }

        /**
        ColumnParent is used when selecting groups of columns from the same ColumnFamily. In directory structure
        terms, imagine
        ColumnParent as ColumnPath + '/../'.
        See also &lt;a href="cassandra.html#Struct_ColumnPath"&gt;ColumnPath&lt;/a&gt;
        */
        public class ColumnParent {
            string column_family; // 3:
            Binary[,,] super_column; // 4:
        }

        /**
        The ColumnPath is the path to a single column in Cassandra. It might make sense to think of ColumnPath and
        ColumnParent in terms of a directory structure.
        ColumnPath is used to looking up a single column.
        @param column_family. The name of the CF of the column being looked up.
        @param super_column. The super column name.
        @param column. The column name.
        */
        public class ColumnPath {
            string column_family; // 3:
            Binary[,,] super_column; // 4:
            Binary[,,] column; // 5:
        }

        /**
        A slice range is a structure that stores basic range, ordering and limit information for a query that will
        return
        multiple columns. It could be thought of as Cassandra's version of LIMIT and ORDER BY
        @param start. The column name to start the slice with. This attribute is not required, though there is no
        default value,
        and can be safely set to '', i.e., an empty byte array, to start with the first column name. Otherwise, it
        must a valid value under the rules of the Comparator defined for the given ColumnFamily.
        @param finish. The column name to stop the slice at. This attribute is not required, though there is no
        default value,
        and can be safely set to an empty byte array to not stop until 'count' results are seen. Otherwise, it
        must also be a valid value to the ColumnFamily Comparator.
        @param reversed. Whether the results should be ordered in reversed order. Similar to ORDER BY blah DESC in
        SQL.
        @param count. How many columns to return. Similar to LIMIT in SQL. May be arbitrarily large, but Thrift will
        materialize the whole result into memory before returning it to the client, so be aware that you may
        be better served by iterating through slices by passing the last value of one call in as the 'start'
        of the next instead of increasing 'count' arbitrarily large.
        */
        public class SliceRange {
            Binary[,,] start; // 1:
            Binary[,,] finish; // 2:
            bool reversed; // 3:
            public const bool reversed_default = false;
            [X] int count; // 4:
            public const int count_default = 100;
        }

        /**
        A SlicePredicate is similar to a mathematic predicate (see
        http://en.wikipedia.org/wiki/Predicate_(mathematical_logic)),
        which is described as "a property that the elements of a set have in common."
        SlicePredicate's in Cassandra are described with either a list of column_names or a SliceRange.  If
        column_names is
        specified, slice_range is ignored.
        @param column_name. A list of column names to retrieve. This can be used similar to Memcached's "multi-get"
        feature
        to fetch N known column names. For instance, if you know you wish to fetch columns 'Joe', 'Jack',
        and 'Jim' you can pass those column names as a list to fetch all three at once.
        @param slice_range. A SliceRange describing how to range, order, and/or limit the slice.
        */
        public class SlicePredicate {
            Binary[,,][,,] column_names; // 1:
            SliceRange slice_range; // 2:
        }

        public class IndexExpression {
            Binary[,,] column_name; // 1:
            IndexOperator op; // 2:
            Binary[,,] value; // 3:
        }

        /**
        @deprecated use a KeyRange with row_filter in get_range_slices instead
        */
        public class IndexClause {
            IndexExpression[,,] expressions; // 1:
            Binary[,,] start_key; // 2:
            [X] int count; // 3:
            public const int count_default = 100;
        }

        /**
        The semantics of start keys and tokens are slightly different.
        Keys are start-inclusive; tokens are start-exclusive.  Token
        ranges may also wrap -- that is, the end token may be less
        than the start one.  Thus, a range from keyX to keyX is a
        one-element range, but a range from tokenY to tokenY is the
        full ring.
        */
        public class KeyRange {
            Binary[,,] start_key; // 1:
            Binary[,,] end_key; // 2:
            string start_token; // 3:
            string end_token; // 4:
            IndexExpression[,,] row_filter; // 6:
            [X] int count; // 5:
            public const int count_default = 100;
        }

        /**
        A KeySlice is key followed by the data it maps to. A collection of KeySlice is returned by the get_range_slice
        operation.
        @param key. a row key
        @param columns. List of data represented by the key. Typically, the list is pared down to only the columns
        specified by
        a SlicePredicate.
        */
        public class KeySlice {
            Binary[,,] key; // 1:
            ColumnOrSuperColumn[,,] columns; // 2:
        }

        public class KeyCount {
            Binary[,,] key; // 1:
            [X] int count; // 2:
        }

        /**
        Note that the timestamp is only optional in case of counter deletion.
        */
        public class Deletion {
            [X] long? timestamp; // 1:
            Binary[,,] super_column; // 2:
            SlicePredicate predicate; // 3:
        }

        /**
        A Mutation is either an insert (represented by filling column_or_supercolumn) or a deletion (represented by
        filling the deletion attribute).
        @param column_or_supercolumn. An insert to a column or supercolumn (possibly counter column or supercolumn)
        @param deletion. A deletion of a column or supercolumn
        */
        public class Mutation {
            ColumnOrSuperColumn column_or_supercolumn; // 1:
            Deletion deletion; // 2:
        }

        public class EndpointDetails {
            string host; // 1:
            string datacenter; // 2:
            string rack; // 3:
        }

        public class CASResult {
            bool success; // 1:
            Column[,,] current_values; // 2:
        }

        /**
        A TokenRange describes part of the Cassandra ring, it is a mapping from a range to
        endpoints responsible for that range.
        @param start_token The first token in the range
        @param end_token The last token in the range
        @param endpoints The endpoints responsible for the range (listed by their configured listen_address)
        @param rpc_endpoints The endpoints responsible for the range (listed by their configured rpc_address)
        */
        public class TokenRange {
            string start_token; // 1:
            string end_token; // 2:
            string[,,] endpoints; // 3:
            string[,,] rpc_endpoints; // 4:
            EndpointDetails[,,] endpoint_details; // 5:
        }

        /**
        Authentication requests can contain any data, dependent on the IAuthenticator used
        */
        public class AuthenticationRequest {
            Map<string, string> credentials; // 1:
        }

        public class ColumnDef {
            Binary[,,] name; // 1:
            string validation_class; // 2:
            IndexType? index_type; // 3:
            string index_name; // 4:
            Map<string, string> index_options; // 5:
        }

        /**
        Describes a trigger.
        `options` should include at least 'class' param.
        Other options are not supported yet.
        */
        public class TriggerDef {
            string name; // 1:
            Map<string, string> options; // 2:
        }

        public class CfDef {
            string keyspace; // 1:
            string name; // 2:
            string column_type; // 3:
            public const string column_type_default = "Standard";
            string comparator_type; // 5:
            public const string comparator_type_default = "BytesType";
            string subcomparator_type; // 6:
            string comment; // 8:
            double? read_repair_chance; // 12:
            ColumnDef[,,] column_metadata; // 13:
            [X] int? gc_grace_seconds; // 14:
            string default_validation_class; // 15:
            [X] int? id; // 16:
            [X] int? min_compaction_threshold; // 17:
            [X] int? max_compaction_threshold; // 18:
            string key_validation_class; // 26:
            Binary[,,] key_alias; // 28:
            string compaction_strategy; // 29:
            Map<string, string> compaction_strategy_options; // 30:
            Map<string, string> compression_options; // 32:
            double? bloom_filter_fp_chance; // 33:
            string caching; // 34:
            public const string caching_default = "keys_only";
            double? dclocal_read_repair_chance; // 37:
            public const double dclocal_read_repair_chance_default = 0.0;
            [X] int? memtable_flush_period_in_ms; // 39:
            [X] int? default_time_to_live; // 40:
            string speculative_retry; // 42:
            public const string speculative_retry_default = "NONE";
            TriggerDef[,,] triggers; // 43:
            string cells_per_row_to_cache; // 44:
            public const string cells_per_row_to_cache_default = "100";
            [X] int? min_index_interval; // 45:
            [X] int? max_index_interval; // 46:
            /**
            @deprecated
            */
            double? row_cache_size; // 9:
            /**
            @deprecated
            */
            double? key_cache_size; // 11:
            /**
            @deprecated
            */
            [X] int? row_cache_save_period_in_seconds; // 19:
            /**
            @deprecated
            */
            [X] int? key_cache_save_period_in_seconds; // 20:
            /**
            @deprecated
            */
            [X] int? memtable_flush_after_mins; // 21:
            /**
            @deprecated
            */
            [X] int? memtable_throughput_in_mb; // 22:
            /**
            @deprecated
            */
            double? memtable_operations_in_millions; // 23:
            /**
            @deprecated
            */
            bool? replicate_on_write; // 24:
            /**
            @deprecated
            */
            double? merge_shards_chance; // 25:
            /**
            @deprecated
            */
            string row_cache_provider; // 27:
            /**
            @deprecated
            */
            [X] int? row_cache_keys_to_save; // 31:
            /**
            @deprecated
            */
            bool? populate_io_cache_on_flush; // 38:
            /**
            @deprecated
            */
            [X] int? index_interval; // 41:
        }

        public class KsDef {
            string name; // 1:
            string strategy_class; // 2:
            Map<string, string> strategy_options; // 3:
            /**
            @deprecated ignored
            */
            [X] int? replication_factor; // 4:
            CfDef[,,] cf_defs; // 5:
            bool? durable_writes; // 6:
            public const bool durable_writes_default = true;
        }

        /**
        Row returned from a CQL query.
        This struct is used for both CQL2 and CQL3 queries.  For CQL2, the partition key
        is special-cased and is always returned.  For CQL3, it is not special cased;
        it will be included in the columns list if it was included in the SELECT and
        the key field is always null.
        */
        public class CqlRow {
            Binary[,,] key; // 1:
            Column[,,] columns; // 2:
        }

        public class CqlMetadata {
            Map<Binary[,,], string> name_types; // 1:
            Map<Binary[,,], string> value_types; // 2:
            string default_name_type; // 3:
            string default_value_type; // 4:
        }

        public class CqlResult {
            CqlResultType Type; // 1:
            CqlRow[,,] rows; // 2:
            [X] int? num; // 3:
            CqlMetadata schema; // 4:
        }

        public class CqlPreparedResult {
            [X] int itemId; // 1:
            [X] int count; // 2:
            string[,,] variable_types; // 3:
            string[,,] variable_names; // 4:
        }

        /**
        Represents input splits used by hadoop ColumnFamilyRecordReaders
        */
        public class CfSplit {
            string start_token; // 1:
            string end_token; // 2:
            [X] long row_count; // 3:
        }

        /**
        The ColumnSlice is used to select a set of columns from inside a row.
        If start or finish are unspecified they will default to the start-of
        end-of value.
        @param start. The start of the ColumnSlice inclusive
        @param finish. The end of the ColumnSlice inclusive
        */
        public class ColumnSlice {
            Binary[,,] start; // 1:
            Binary[,,] finish; // 2:
        }

        /**
        Used to perform multiple slices on a single row key in one rpc operation
        @param key. The row key to be multi sliced
        @param column_parent. The column family (super columns are unsupported)
        @param column_slices. 0 to many ColumnSlice objects each will be used to select columns
        @param reversed. Direction of slice
        @param count. Maximum number of columns
        @param consistency_level. Level to perform the operation at
        */
        public class MultiSliceRequest {
            Binary[,,] key; // 1:
            ColumnParent column_parent; // 2:
            ColumnSlice[,,] column_slices; // 3:
            bool? reversed; // 4:
            public const bool reversed_default = false;
            [X] int? count; // 5:
            public const int count_default = 1000;
            ConsistencyLevel? consistency_level; // 6:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        // ───── packs of service Cassandra ─────

        /**
        auth methods
        Arguments of Cassandra.login().
        */
        public class Cassandra_login_Args {
            AuthenticationRequest auth_request; // 1:
        }

        /**
        Result of Cassandra.login() (void).
        */
        public class Cassandra_login_Result {
        }

        /**
        set keyspace
        Arguments of Cassandra.set_keyspace().
        */
        public class Cassandra_set_keyspace_Args {
            string keyspace; // 1:
        }

        /**
        Result of Cassandra.set_keyspace() (void).
        */
        public class Cassandra_set_keyspace_Result {
        }

        /**
        retrieval methods
        Get the Column or SuperColumn at the given column_path. If no value is present, NotFoundException is thrown.
        (This is
        the only method that can throw an exception under non-failure conditions.)
        Arguments of Cassandra.get().
        */
        public class Cassandra_get_Args {
            Binary[,,] key; // 1:
            ColumnPath column_path; // 2:
            ConsistencyLevel consistency_level; // 3:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.get().
        */
        public class Cassandra_get_Result {
            ColumnOrSuperColumn success; // 0:
        }

        /**
        Get the group of columns contained by column_parent (either a ColumnFamily name or a ColumnFamily/SuperColumn
        name
        pair) specified by the given SlicePredicate. If no matching values are found, an empty list is returned.
        Arguments of Cassandra.get_slice().
        */
        public class Cassandra_get_slice_Args {
            Binary[,,] key; // 1:
            ColumnParent column_parent; // 2:
            SlicePredicate predicate; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.get_slice().
        */
        public class Cassandra_get_slice_Result {
            ColumnOrSuperColumn[,,] success; // 0:
        }

        /**
        returns the number of columns matching &lt;code&gt;predicate&lt;/code&gt; for a particular
        &lt;code&gt;key&lt;/code&gt;,
        &lt;code&gt;ColumnFamily&lt;/code&gt; and optionally &lt;code&gt;SuperColumn&lt;/code&gt;.
        Arguments of Cassandra.get_count().
        */
        public class Cassandra_get_count_Args {
            Binary[,,] key; // 1:
            ColumnParent column_parent; // 2:
            SlicePredicate predicate; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.get_count().
        */
        public class Cassandra_get_count_Result {
            [X] int success; // 0:
        }

        /**
        Performs a get_slice for column_parent and predicate for the given keys in parallel.
        Arguments of Cassandra.multiget_slice().
        */
        public class Cassandra_multiget_slice_Args {
            Binary[,,][,,] keys; // 1:
            ColumnParent column_parent; // 2:
            SlicePredicate predicate; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.multiget_slice().
        */
        public class Cassandra_multiget_slice_Result {
            Map<Binary[,,], ColumnOrSuperColumn[,,]> success; // 0:
        }

        /**
        Perform a get_count in parallel on the given list&lt;binary&gt; keys. The return value maps keys to the count
        found.
        Arguments of Cassandra.multiget_count().
        */
        public class Cassandra_multiget_count_Args {
            Binary[,,][,,] keys; // 1:
            ColumnParent column_parent; // 2:
            SlicePredicate predicate; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.multiget_count().
        */
        public class Cassandra_multiget_count_Result {
            [Val: X] Map<Binary[,,], int> success; // 0:
        }

        /**
        returns a subset of columns for a contiguous range of keys.
        Arguments of Cassandra.get_range_slices().
        */
        public class Cassandra_get_range_slices_Args {
            ColumnParent column_parent; // 1:
            SlicePredicate predicate; // 2:
            KeyRange Range; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.get_range_slices().
        */
        public class Cassandra_get_range_slices_Result {
            KeySlice[,,] success; // 0:
        }

        /**
        returns a range of columns, wrapping to the next rows if necessary to collect max_results.
        Arguments of Cassandra.get_paged_slice().
        */
        public class Cassandra_get_paged_slice_Args {
            string column_family; // 1:
            KeyRange Range; // 2:
            Binary[,,] start_column; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.get_paged_slice().
        */
        public class Cassandra_get_paged_slice_Result {
            KeySlice[,,] success; // 0:
        }

        /**
        Returns the subset of columns specified in SlicePredicate for the rows matching the IndexClause
        @deprecated use get_range_slices instead with range.row_filter specified
        Arguments of Cassandra.get_indexed_slices().
        */
        public class Cassandra_get_indexed_slices_Args {
            ColumnParent column_parent; // 1:
            IndexClause index_clause; // 2:
            SlicePredicate column_predicate; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.get_indexed_slices().
        */
        public class Cassandra_get_indexed_slices_Result {
            KeySlice[,,] success; // 0:
        }

        /**
        modification methods
        Insert a Column at the given column_parent.column_family and optional column_parent.super_column.
        Arguments of Cassandra.insert().
        */
        public class Cassandra_insert_Args {
            Binary[,,] key; // 1:
            ColumnParent column_parent; // 2:
            Column column; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.insert() (void).
        */
        public class Cassandra_insert_Result {
        }

        /**
        Increment or decrement a counter.
        Arguments of Cassandra.add().
        */
        public class Cassandra_add_Args {
            Binary[,,] key; // 1:
            ColumnParent column_parent; // 2:
            CounterColumn column; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.add() (void).
        */
        public class Cassandra_add_Result {
        }

        /**
        Atomic compare and set.
        If the cas is successfull, the success boolean in CASResult will be true and there will be no current_values.
        Otherwise, success will be false and current_values will contain the current values for the columns in
        expected (that, by definition of compare-and-set, will differ from the values in expected).
        A cas operation takes 2 consistency level. The first one, serial_consistency_level, simply indicates the
        level of serialization required. This can be either ConsistencyLevel.SERIAL or ConsistencyLevel.LOCAL_SERIAL.
        The second one, commit_consistency_level, defines the consistency level for the commit phase of the cas. This
        is a more traditional consistency level (the same CL than for traditional writes are accepted) that impact
        the visibility for reads of the operation. For instance, if commit_consistency_level is QUORUM, then it is
        guaranteed that a followup QUORUM read will see the cas write (if that one was successful obviously). If
        commit_consistency_level is ANY, you will need to use a SERIAL/LOCAL_SERIAL read to be guaranteed to see
        the write.
        Arguments of Cassandra.cas().
        */
        public class Cassandra_cas_Args {
            Binary[,,] key; // 1:
            string column_family; // 2:
            Column[,,] expected; // 3:
            Column[,,] updates; // 4:
            ConsistencyLevel serial_consistency_level; // 5:
            public const int serial_consistency_level_default = 9; // ConsistencyLevel.SERIAL
            ConsistencyLevel commit_consistency_level; // 6:
            public const int commit_consistency_level_default = 2; // ConsistencyLevel.QUORUM
        }

        /**
        Result of Cassandra.cas().
        */
        public class Cassandra_cas_Result {
            CASResult success; // 0:
        }

        /**
        Remove data from the row specified by key at the granularity specified by column_path, and the given
        timestamp. Note
        that all the values in column_path besides column_path.column_family are truly optional: you can remove the
        entire
        row by just specifying the ColumnFamily, or you can remove a SuperColumn or a single Column by specifying
        those levels too.
        Arguments of Cassandra.remove().
        */
        public class Cassandra_remove_Args {
            Binary[,,] key; // 1:
            ColumnPath column_path; // 2:
            [X] long timestamp; // 3:
            ConsistencyLevel consistency_level; // 4:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.remove() (void).
        */
        public class Cassandra_remove_Result {
        }

        /**
        Remove a counter at the specified location.
        Note that counters have limited support for deletes: if you remove a counter, you must wait to issue any
        following update
        until the delete has reached all the nodes and all of them have been fully compacted.
        Arguments of Cassandra.remove_counter().
        */
        public class Cassandra_remove_counter_Args {
            Binary[,,] key; // 1:
            ColumnPath path; // 2:
            ConsistencyLevel consistency_level; // 3:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.remove_counter() (void).
        */
        public class Cassandra_remove_counter_Result {
        }

        /**
        Mutate many columns or super columns for many row keys. See also: Mutation.
        mutation_map maps key to column family to a list of Mutation objects to take place at that scope.
        Arguments of Cassandra.batch_mutate().
        */
        public class Cassandra_batch_mutate_Args {
            Map<Binary[,,], Wrap_Map_string_to_List_Mutation> mutation_map; // 1:
            ConsistencyLevel consistency_level; // 2:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.batch_mutate() (void).
        */
        public class Cassandra_batch_mutate_Result {
        }

        /**
        Atomically mutate many columns or super columns for many row keys. See also: Mutation.
        mutation_map maps key to column family to a list of Mutation objects to take place at that scope.
        Arguments of Cassandra.atomic_batch_mutate().
        */
        public class Cassandra_atomic_batch_mutate_Args {
            Map<Binary[,,], Wrap_Map_string_to_List_Mutation> mutation_map; // 1:
            ConsistencyLevel consistency_level; // 2:
            public const int consistency_level_default = 1; // ConsistencyLevel.ONE
        }

        /**
        Result of Cassandra.atomic_batch_mutate() (void).
        */
        public class Cassandra_atomic_batch_mutate_Result {
        }

        /**
        Truncate will mark and entire column family as deleted.
        From the user's perspective a successful call to truncate will result complete data deletion from cfname.
        Internally, however, disk space will not be immediatily released, as with all deletes in cassandra, this one
        only marks the data as deleted.
        The operation succeeds only if all hosts in the cluster at available and will throw an UnavailableException if
        some hosts are down.
        Arguments of Cassandra.truncate().
        */
        public class Cassandra_truncate_Args {
            string cfname; // 1:
        }

        /**
        Result of Cassandra.truncate() (void).
        */
        public class Cassandra_truncate_Result {
        }

        /**
        Select multiple slices of a key in a single RPC operation
        Arguments of Cassandra.get_multi_slice().
        */
        public class Cassandra_get_multi_slice_Args {
            MultiSliceRequest request; // 1:
        }

        /**
        Result of Cassandra.get_multi_slice().
        */
        public class Cassandra_get_multi_slice_Result {
            ColumnOrSuperColumn[,,] success; // 0:
        }

        /**
        Meta-APIs -- APIs to get information about the node or cluster,
        rather than user data.  The nodeprobe program provides usage examples.
        for each schema version present in the cluster, returns a list of nodes at that version.
        hosts that do not respond will be under the key DatabaseDescriptor.INITIAL_VERSION.
        the cluster is all on the same version if the size of the map is 1.
        Arguments of Cassandra.describe_schema_versions().
        */
        public class Cassandra_describe_schema_versions_Args {
        }

        /**
        Result of Cassandra.describe_schema_versions().
        */
        public class Cassandra_describe_schema_versions_Result {
            Map<string, string[,,]> success; // 0:
        }

        /**
        list the defined keyspaces in this cluster
        Arguments of Cassandra.describe_keyspaces().
        */
        public class Cassandra_describe_keyspaces_Args {
        }

        /**
        Result of Cassandra.describe_keyspaces().
        */
        public class Cassandra_describe_keyspaces_Result {
            KsDef[,,] success; // 0:
        }

        /**
        get the cluster name
        Arguments of Cassandra.describe_cluster_name().
        */
        public class Cassandra_describe_cluster_name_Args {
        }

        /**
        Result of Cassandra.describe_cluster_name().
        */
        public class Cassandra_describe_cluster_name_Result {
            string success; // 0:
        }

        /**
        get the thrift api version
        Arguments of Cassandra.describe_version().
        */
        public class Cassandra_describe_version_Args {
        }

        /**
        Result of Cassandra.describe_version().
        */
        public class Cassandra_describe_version_Result {
            string success; // 0:
        }

        /**
        get the token ring: a map of ranges to host addresses,
        represented as a set of TokenRange instead of a map from range
        to list of endpoints, because you can't use Thrift structs as
        map keys:
        https://issues.apache.org/jira/browse/THRIFT-162
        for the same reason, we can't return a set here, even though
        order is neither important nor predictable.
        Arguments of Cassandra.describe_ring().
        */
        public class Cassandra_describe_ring_Args {
            string keyspace; // 1:
        }

        /**
        Result of Cassandra.describe_ring().
        */
        public class Cassandra_describe_ring_Result {
            TokenRange[,,] success; // 0:
        }

        /**
        same as describe_ring, but considers only nodes in the local DC
        Arguments of Cassandra.describe_local_ring().
        */
        public class Cassandra_describe_local_ring_Args {
            string keyspace; // 1:
        }

        /**
        Result of Cassandra.describe_local_ring().
        */
        public class Cassandra_describe_local_ring_Result {
            TokenRange[,,] success; // 0:
        }

        /**
        get the mapping between token-&gt;node ip
        without taking replication into consideration
        https://issues.apache.org/jira/browse/CASSANDRA-4092
        Arguments of Cassandra.describe_token_map().
        */
        public class Cassandra_describe_token_map_Args {
        }

        /**
        Result of Cassandra.describe_token_map().
        */
        public class Cassandra_describe_token_map_Result {
            Map<string, string> success; // 0:
        }

        /**
        returns the partitioner used by this cluster
        Arguments of Cassandra.describe_partitioner().
        */
        public class Cassandra_describe_partitioner_Args {
        }

        /**
        Result of Cassandra.describe_partitioner().
        */
        public class Cassandra_describe_partitioner_Result {
            string success; // 0:
        }

        /**
        returns the snitch used by this cluster
        Arguments of Cassandra.describe_snitch().
        */
        public class Cassandra_describe_snitch_Args {
        }

        /**
        Result of Cassandra.describe_snitch().
        */
        public class Cassandra_describe_snitch_Result {
            string success; // 0:
        }

        /**
        describe specified keyspace
        Arguments of Cassandra.describe_keyspace().
        */
        public class Cassandra_describe_keyspace_Args {
            string keyspace; // 1:
        }

        /**
        Result of Cassandra.describe_keyspace().
        */
        public class Cassandra_describe_keyspace_Result {
            KsDef success; // 0:
        }

        /**
        experimental API for hadoop/parallel query support.
        may change violently and without warning.
        returns list of token strings such that first subrange is (list[0], list[1]],
        next is (list[1], list[2]], etc.
        Arguments of Cassandra.describe_splits().
        */
        public class Cassandra_describe_splits_Args {
            string cfName; // 1:
            string start_token; // 2:
            string end_token; // 3:
            [X] int keys_per_split; // 4:
        }

        /**
        Result of Cassandra.describe_splits().
        */
        public class Cassandra_describe_splits_Result {
            string[,,] success; // 0:
        }

        /**
        Enables tracing for the next query in this connection and returns the UUID for that trace session
        The next query will be traced idependently of trace probability and the returned UUID can be used to query the
        trace keyspace
        Arguments of Cassandra.trace_next_query().
        */
        public class Cassandra_trace_next_query_Args {
        }

        /**
        Result of Cassandra.trace_next_query().
        */
        public class Cassandra_trace_next_query_Result {
            Binary[,,] success; // 0:
        }

        /**
        Arguments of Cassandra.describe_splits_ex().
        */
        public class Cassandra_describe_splits_ex_Args {
            string cfName; // 1:
            string start_token; // 2:
            string end_token; // 3:
            [X] int keys_per_split; // 4:
        }

        /**
        Result of Cassandra.describe_splits_ex().
        */
        public class Cassandra_describe_splits_ex_Result {
            CfSplit[,,] success; // 0:
        }

        /**
        adds a column family. returns the new schema id.
        Arguments of Cassandra.system_add_column_family().
        */
        public class Cassandra_system_add_column_family_Args {
            CfDef cf_def; // 1:
        }

        /**
        Result of Cassandra.system_add_column_family().
        */
        public class Cassandra_system_add_column_family_Result {
            string success; // 0:
        }

        /**
        drops a column family. returns the new schema id.
        Arguments of Cassandra.system_drop_column_family().
        */
        public class Cassandra_system_drop_column_family_Args {
            string column_family; // 1:
        }

        /**
        Result of Cassandra.system_drop_column_family().
        */
        public class Cassandra_system_drop_column_family_Result {
            string success; // 0:
        }

        /**
        adds a keyspace and any column families that are part of it. returns the new schema id.
        Arguments of Cassandra.system_add_keyspace().
        */
        public class Cassandra_system_add_keyspace_Args {
            KsDef ks_def; // 1:
        }

        /**
        Result of Cassandra.system_add_keyspace().
        */
        public class Cassandra_system_add_keyspace_Result {
            string success; // 0:
        }

        /**
        drops a keyspace and any column families that are part of it. returns the new schema id.
        Arguments of Cassandra.system_drop_keyspace().
        */
        public class Cassandra_system_drop_keyspace_Args {
            string keyspace; // 1:
        }

        /**
        Result of Cassandra.system_drop_keyspace().
        */
        public class Cassandra_system_drop_keyspace_Result {
            string success; // 0:
        }

        /**
        updates properties of a keyspace. returns the new schema id.
        Arguments of Cassandra.system_update_keyspace().
        */
        public class Cassandra_system_update_keyspace_Args {
            KsDef ks_def; // 1:
        }

        /**
        Result of Cassandra.system_update_keyspace().
        */
        public class Cassandra_system_update_keyspace_Result {
            string success; // 0:
        }

        /**
        updates properties of a column family. returns the new schema id.
        Arguments of Cassandra.system_update_column_family().
        */
        public class Cassandra_system_update_column_family_Args {
            CfDef cf_def; // 1:
        }

        /**
        Result of Cassandra.system_update_column_family().
        */
        public class Cassandra_system_update_column_family_Result {
            string success; // 0:
        }

        /**
        @deprecated Throws InvalidRequestException since 2.2. Please use the CQL3 version instead.
        Arguments of Cassandra.execute_cql_query().
        */
        public class Cassandra_execute_cql_query_Args {
            Binary[,,] query; // 1:
            Compression compression; // 2:
        }

        /**
        Result of Cassandra.execute_cql_query().
        */
        public class Cassandra_execute_cql_query_Result {
            CqlResult success; // 0:
        }

        /**
        Executes a CQL3 (Cassandra Query Language) statement and returns a
        CqlResult containing the results.
        Arguments of Cassandra.execute_cql3_query().
        */
        public class Cassandra_execute_cql3_query_Args {
            Binary[,,] query; // 1:
            Compression compression; // 2:
            ConsistencyLevel consistency; // 3:
        }

        /**
        Result of Cassandra.execute_cql3_query().
        */
        public class Cassandra_execute_cql3_query_Result {
            CqlResult success; // 0:
        }

        /**
        @deprecated Throws InvalidRequestException since 2.2. Please use the CQL3 version instead.
        Arguments of Cassandra.prepare_cql_query().
        */
        public class Cassandra_prepare_cql_query_Args {
            Binary[,,] query; // 1:
            Compression compression; // 2:
        }

        /**
        Result of Cassandra.prepare_cql_query().
        */
        public class Cassandra_prepare_cql_query_Result {
            CqlPreparedResult success; // 0:
        }

        /**
        Prepare a CQL3 (Cassandra Query Language) statement by compiling and returning
        - the type of CQL statement
        - an id token of the compiled CQL stored on the server side.
        - a count of the discovered bound markers in the statement
        Arguments of Cassandra.prepare_cql3_query().
        */
        public class Cassandra_prepare_cql3_query_Args {
            Binary[,,] query; // 1:
            Compression compression; // 2:
        }

        /**
        Result of Cassandra.prepare_cql3_query().
        */
        public class Cassandra_prepare_cql3_query_Result {
            CqlPreparedResult success; // 0:
        }

        /**
        @deprecated Throws InvalidRequestException since 2.2. Please use the CQL3 version instead.
        Arguments of Cassandra.execute_prepared_cql_query().
        */
        public class Cassandra_execute_prepared_cql_query_Args {
            [X] int itemId; // 1:
            Binary[,,][,,] values; // 2:
        }

        /**
        Result of Cassandra.execute_prepared_cql_query().
        */
        public class Cassandra_execute_prepared_cql_query_Result {
            CqlResult success; // 0:
        }

        /**
        Executes a prepared CQL3 (Cassandra Query Language) statement by passing an id token, a list of variables
        to bind, and the consistency level, and returns a CqlResult containing the results.
        Arguments of Cassandra.execute_prepared_cql3_query().
        */
        public class Cassandra_execute_prepared_cql3_query_Args {
            [X] int itemId; // 1:
            Binary[,,][,,] values; // 2:
            ConsistencyLevel consistency; // 3:
        }

        /**
        Result of Cassandra.execute_prepared_cql3_query().
        */
        public class Cassandra_execute_prepared_cql3_query_Result {
            CqlResult success; // 0:
        }

        /**
        @deprecated This is now a no-op. Please use the CQL3 specific methods instead.
        Arguments of Cassandra.set_cql_version().
        */
        public class Cassandra_set_cql_version_Args {
            string version; // 1:
        }

        /**
        Result of Cassandra.set_cql_version() (void).
        */
        public class Cassandra_set_cql_version_Result {
        }

        // ═════════════════════════ wrappers: a Set/Map/uuid nested inside a Set or Map ═════════════════════════

        public class Wrap_Map_string_to_List_Mutation { Map<string, Mutation[,,]> value; }

        // ═════════════════════════ topology ═════════════════════════

        // Calls the services (Left side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // Implements the services (Right side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface ClientServer : Connects<Client, Server> {

            /**
            Thrift service Cassandra
            */
            interface Cassandra {
                (L____________, Cassandra_login_Result, AuthenticationException, AuthorizationException) login(Cassandra_login_Args req);
                (L____________, Cassandra_set_keyspace_Result, InvalidRequestException) set_keyspace(Cassandra_set_keyspace_Args req);
                (L____________, Cassandra_get_Result, InvalidRequestException, NotFoundException, UnavailableException, TimedOutException) get(Cassandra_get_Args req);
                (L____________, Cassandra_get_slice_Result, InvalidRequestException, UnavailableException, TimedOutException) get_slice(Cassandra_get_slice_Args req);
                (L____________, Cassandra_get_count_Result, InvalidRequestException, UnavailableException, TimedOutException) get_count(Cassandra_get_count_Args req);
                (L____________, Cassandra_multiget_slice_Result, InvalidRequestException, UnavailableException, TimedOutException) multiget_slice(Cassandra_multiget_slice_Args req);
                (L____________, Cassandra_multiget_count_Result, InvalidRequestException, UnavailableException, TimedOutException) multiget_count(Cassandra_multiget_count_Args req);
                (L____________, Cassandra_get_range_slices_Result, InvalidRequestException, UnavailableException, TimedOutException) get_range_slices(Cassandra_get_range_slices_Args req);
                (L____________, Cassandra_get_paged_slice_Result, InvalidRequestException, UnavailableException, TimedOutException) get_paged_slice(Cassandra_get_paged_slice_Args req);
                (L____________, Cassandra_get_indexed_slices_Result, InvalidRequestException, UnavailableException, TimedOutException) get_indexed_slices(Cassandra_get_indexed_slices_Args req);
                (L____________, Cassandra_insert_Result, InvalidRequestException, UnavailableException, TimedOutException) insert(Cassandra_insert_Args req);
                (L____________, Cassandra_add_Result, InvalidRequestException, UnavailableException, TimedOutException) add(Cassandra_add_Args req);
                (L____________, Cassandra_cas_Result, InvalidRequestException, UnavailableException, TimedOutException) cas(Cassandra_cas_Args req);
                (L____________, Cassandra_remove_Result, InvalidRequestException, UnavailableException, TimedOutException) remove(Cassandra_remove_Args req);
                (L____________, Cassandra_remove_counter_Result, InvalidRequestException, UnavailableException, TimedOutException) remove_counter(Cassandra_remove_counter_Args req);
                (L____________, Cassandra_batch_mutate_Result, InvalidRequestException, UnavailableException, TimedOutException) batch_mutate(Cassandra_batch_mutate_Args req);
                (L____________, Cassandra_atomic_batch_mutate_Result, InvalidRequestException, UnavailableException, TimedOutException) atomic_batch_mutate(Cassandra_atomic_batch_mutate_Args req);
                (L____________, Cassandra_truncate_Result, InvalidRequestException, UnavailableException, TimedOutException) truncate(Cassandra_truncate_Args req);
                (L____________, Cassandra_get_multi_slice_Result, InvalidRequestException, UnavailableException, TimedOutException) get_multi_slice(Cassandra_get_multi_slice_Args req);
                (L____________, Cassandra_describe_schema_versions_Result, InvalidRequestException) describe_schema_versions(Cassandra_describe_schema_versions_Args req);
                (L____________, Cassandra_describe_keyspaces_Result, InvalidRequestException) describe_keyspaces(Cassandra_describe_keyspaces_Args req);
                (L____________, Cassandra_describe_cluster_name_Result) describe_cluster_name(Cassandra_describe_cluster_name_Args req);
                (L____________, Cassandra_describe_version_Result) describe_version(Cassandra_describe_version_Args req);
                (L____________, Cassandra_describe_ring_Result, InvalidRequestException) describe_ring(Cassandra_describe_ring_Args req);
                (L____________, Cassandra_describe_local_ring_Result, InvalidRequestException) describe_local_ring(Cassandra_describe_local_ring_Args req);
                (L____________, Cassandra_describe_token_map_Result, InvalidRequestException) describe_token_map(Cassandra_describe_token_map_Args req);
                (L____________, Cassandra_describe_partitioner_Result) describe_partitioner(Cassandra_describe_partitioner_Args req);
                (L____________, Cassandra_describe_snitch_Result) describe_snitch(Cassandra_describe_snitch_Args req);
                (L____________, Cassandra_describe_keyspace_Result, NotFoundException, InvalidRequestException) describe_keyspace(Cassandra_describe_keyspace_Args req);
                (L____________, Cassandra_describe_splits_Result, InvalidRequestException) describe_splits(Cassandra_describe_splits_Args req);
                (L____________, Cassandra_trace_next_query_Result) trace_next_query(Cassandra_trace_next_query_Args req);
                (L____________, Cassandra_describe_splits_ex_Result, InvalidRequestException) describe_splits_ex(Cassandra_describe_splits_ex_Args req);
                (L____________, Cassandra_system_add_column_family_Result, InvalidRequestException, SchemaDisagreementException) system_add_column_family(Cassandra_system_add_column_family_Args req);
                (L____________, Cassandra_system_drop_column_family_Result, InvalidRequestException, SchemaDisagreementException) system_drop_column_family(Cassandra_system_drop_column_family_Args req);
                (L____________, Cassandra_system_add_keyspace_Result, InvalidRequestException, SchemaDisagreementException) system_add_keyspace(Cassandra_system_add_keyspace_Args req);
                (L____________, Cassandra_system_drop_keyspace_Result, InvalidRequestException, SchemaDisagreementException) system_drop_keyspace(Cassandra_system_drop_keyspace_Args req);
                (L____________, Cassandra_system_update_keyspace_Result, InvalidRequestException, SchemaDisagreementException) system_update_keyspace(Cassandra_system_update_keyspace_Args req);
                (L____________, Cassandra_system_update_column_family_Result, InvalidRequestException, SchemaDisagreementException) system_update_column_family(Cassandra_system_update_column_family_Args req);
                (L____________, Cassandra_execute_cql_query_Result, InvalidRequestException, UnavailableException, TimedOutException, SchemaDisagreementException) execute_cql_query(Cassandra_execute_cql_query_Args req);
                (L____________, Cassandra_execute_cql3_query_Result, InvalidRequestException, UnavailableException, TimedOutException, SchemaDisagreementException) execute_cql3_query(Cassandra_execute_cql3_query_Args req);
                (L____________, Cassandra_prepare_cql_query_Result, InvalidRequestException) prepare_cql_query(Cassandra_prepare_cql_query_Args req);
                (L____________, Cassandra_prepare_cql3_query_Result, InvalidRequestException) prepare_cql3_query(Cassandra_prepare_cql3_query_Args req);
                (L____________, Cassandra_execute_prepared_cql_query_Result, InvalidRequestException, UnavailableException, TimedOutException, SchemaDisagreementException) execute_prepared_cql_query(Cassandra_execute_prepared_cql_query_Args req);
                (L____________, Cassandra_execute_prepared_cql3_query_Result, InvalidRequestException, UnavailableException, TimedOutException, SchemaDisagreementException) execute_prepared_cql3_query(Cassandra_execute_prepared_cql3_query_Args req);
                (L____________, Cassandra_set_cql_version_Result, InvalidRequestException) set_cql_version(Cassandra_set_cql_version_Args req);
            }
        }

        // ═════════════════════════ Thrift metadata attribute ═════════════════════════

        // Not read by AdHoc; kept so a Thrift annotation survives the conversion.

        /** Thrift annotation `(key = "value")` on the field or its type. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AnnotationAttribute : Attribute { public AnnotationAttribute(string key, string value) { } }
    }
}
