// Generated by Thrift2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: fb303.thrift
// fb303.thrift: namespace java com.facebook.fb303
// fb303.thrift: namespace cpp facebook.fb303
// fb303.thrift: namespace perl Facebook.FB303
// fb303.thrift: namespace netstd Facebook.FB303.Test
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.thrift {
    /**
        <see cref = 'FacebookService_aliveSince_Args'/>
        <see cref = 'FacebookService_aliveSince_Result'/>
        <see cref = 'FacebookService_getCounter_Args'/>
        <see cref = 'FacebookService_getCounter_Result'/>
        <see cref = 'FacebookService_getCounters_Args'/>
        <see cref = 'FacebookService_getCounters_Result'/>
        <see cref = 'FacebookService_getCpuProfile_Args'/>
        <see cref = 'FacebookService_getCpuProfile_Result'/>
        <see cref = 'FacebookService_getName_Args'/>
        <see cref = 'FacebookService_getName_Result'/>
        <see cref = 'FacebookService_getOption_Args'/>
        <see cref = 'FacebookService_getOption_Result'/>
        <see cref = 'FacebookService_getOptions_Args'/>
        <see cref = 'FacebookService_getOptions_Result'/>
        <see cref = 'FacebookService_getStatusDetails_Args'/>
        <see cref = 'FacebookService_getStatusDetails_Result'/>
        <see cref = 'FacebookService_getStatus_Args'/>
        <see cref = 'FacebookService_getStatus_Result'/>
        <see cref = 'FacebookService_getVersion_Args'/>
        <see cref = 'FacebookService_getVersion_Result'/>
        <see cref = 'FacebookService_reinitialize_Args'/>
        <see cref = 'FacebookService_setOption_Args'/>
        <see cref = 'FacebookService_setOption_Result'/>
        <see cref = 'FacebookService_shutdown_Args'/>
    */
    public interface fb303 {
        // A trailing `// N:` on a field is its Thrift field id; `<field>_default` is the field's Thrift default.
        // Neither is read by AdHoc.
        // Thrift declares no size bounds. These permissive defaults replace AdHoc's 255 limit;
        // add [D(+N)] on a field whose real bound is known.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        // ═════════════════════════ fb303.thrift ═════════════════════════

        /**
        Common status reporting mechanism across all services
        */
        enum fb_status {
            DEAD = 0,
            STARTING = 1,
            ALIVE = 2,
            STOPPING = 3,
            STOPPED = 4,
            WARNING = 5,
        }

        // ───── packs of service FacebookService ─────

        /**
        Returns a descriptive name of the service
        Arguments of FacebookService.getName().
        */
        public class FacebookService_getName_Args {
        }

        /**
        Result of FacebookService.getName().
        */
        public class FacebookService_getName_Result {
            string success; // 0:
        }

        /**
        Returns the version of the service
        Arguments of FacebookService.getVersion().
        */
        public class FacebookService_getVersion_Args {
        }

        /**
        Result of FacebookService.getVersion().
        */
        public class FacebookService_getVersion_Result {
            string success; // 0:
        }

        /**
        Gets the status of this service
        Arguments of FacebookService.getStatus().
        */
        public class FacebookService_getStatus_Args {
        }

        /**
        Result of FacebookService.getStatus().
        */
        public class FacebookService_getStatus_Result {
            fb_status success; // 0:
        }

        /**
        User friendly description of status, such as why the service is in
        the dead or warning state, or what is being started or stopped.
        Arguments of FacebookService.getStatusDetails().
        */
        public class FacebookService_getStatusDetails_Args {
        }

        /**
        Result of FacebookService.getStatusDetails().
        */
        public class FacebookService_getStatusDetails_Result {
            string success; // 0:
        }

        /**
        Gets the counters for this service
        Arguments of FacebookService.getCounters().
        */
        public class FacebookService_getCounters_Args {
        }

        /**
        Result of FacebookService.getCounters().
        */
        public class FacebookService_getCounters_Result {
            [Val: X] Map<string, long> success; // 0:
        }

        /**
        Gets the value of a single counter
        Arguments of FacebookService.getCounter().
        */
        public class FacebookService_getCounter_Args {
            string key; // 1:
        }

        /**
        Result of FacebookService.getCounter().
        */
        public class FacebookService_getCounter_Result {
            [X] long success; // 0:
        }

        /**
        Sets an option
        Arguments of FacebookService.setOption().
        */
        public class FacebookService_setOption_Args {
            string key; // 1:
            string value; // 2:
        }

        /**
        Result of FacebookService.setOption() (void).
        */
        public class FacebookService_setOption_Result {
        }

        /**
        Gets an option
        Arguments of FacebookService.getOption().
        */
        public class FacebookService_getOption_Args {
            string key; // 1:
        }

        /**
        Result of FacebookService.getOption().
        */
        public class FacebookService_getOption_Result {
            string success; // 0:
        }

        /**
        Gets all options
        Arguments of FacebookService.getOptions().
        */
        public class FacebookService_getOptions_Args {
        }

        /**
        Result of FacebookService.getOptions().
        */
        public class FacebookService_getOptions_Result {
            Map<string, string> success; // 0:
        }

        /**
        Returns a CPU profile over the given time interval (client and server
        must agree on the profile format).
        Arguments of FacebookService.getCpuProfile().
        */
        public class FacebookService_getCpuProfile_Args {
            [X] int profileDurationInSec; // 1:
        }

        /**
        Result of FacebookService.getCpuProfile().
        */
        public class FacebookService_getCpuProfile_Result {
            string success; // 0:
        }

        /**
        Returns the unix time that the server has been running since
        Arguments of FacebookService.aliveSince().
        */
        public class FacebookService_aliveSince_Args {
        }

        /**
        Result of FacebookService.aliveSince().
        */
        public class FacebookService_aliveSince_Result {
            [X] long success; // 0:
        }

        /**
        Tell the server to reload its configuration, reopen log files, etc
        Arguments of FacebookService.reinitialize().
        */
        public class FacebookService_reinitialize_Args {
        }

        /**
        Suggest a shutdown to the server
        Arguments of FacebookService.shutdown().
        */
        public class FacebookService_shutdown_Args {
        }

        // ═════════════════════════ topology ═════════════════════════

        // Calls the services (Left side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // Implements the services (Right side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface ClientServer : Connects<Client, Server> {

            /**
            Thrift service FacebookService
            Standard base service
            */
            interface FacebookService {
                (L____________, FacebookService_getName_Result) getName(FacebookService_getName_Args req);
                (L____________, FacebookService_getVersion_Result) getVersion(FacebookService_getVersion_Args req);
                (L____________, FacebookService_getStatus_Result) getStatus(FacebookService_getStatus_Args req);
                (L____________, FacebookService_getStatusDetails_Result) getStatusDetails(FacebookService_getStatusDetails_Args req);
                (L____________, FacebookService_getCounters_Result) getCounters(FacebookService_getCounters_Args req);
                (L____________, FacebookService_getCounter_Result) getCounter(FacebookService_getCounter_Args req);
                (L____________, FacebookService_setOption_Result) setOption(FacebookService_setOption_Args req);
                (L____________, FacebookService_getOption_Result) getOption(FacebookService_getOption_Args req);
                (L____________, FacebookService_getOptions_Result) getOptions(FacebookService_getOptions_Args req);
                (L____________, FacebookService_getCpuProfile_Result) getCpuProfile(FacebookService_getCpuProfile_Args req);
                (L____________, FacebookService_aliveSince_Result) aliveSince(FacebookService_aliveSince_Args req);
                // oneway reinitialize(): see state FacebookService_reinitialize of the connection
                // oneway shutdown(): see state FacebookService_shutdown of the connection
            }

            // oneway methods: fire-and-forget states of the connection's default actor
            [l____________<FacebookService_reinitialize_Args>]
            struct FacebookService_reinitialize { }
            [l____________<FacebookService_shutdown_Args>]
            struct FacebookService_shutdown { }
        }

        // ═════════════════════════ Thrift metadata attribute ═════════════════════════

        // Not read by AdHoc; kept so a Thrift annotation survives the conversion.

        /** Thrift annotation `(key = "value")` on the field or its type. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AnnotationAttribute : Attribute { public AnnotationAttribute(string key, string value) { } }
    }
}
