// Generated by Thrift2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: jaeger.thrift
// jaeger.thrift: namespace cpp jaegertracing.thrift
// jaeger.thrift: namespace java io.jaegertracing.thriftjava
// jaeger.thrift: namespace php Jaeger.Thrift
// jaeger.thrift: namespace netstd Jaeger.Thrift
// jaeger.thrift: namespace lua jaeger.thrift
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.thrift {
    /**
        <see cref = 'Batch'/>
        <see cref = 'BatchSubmitResponse'/>
        <see cref = 'ClientStats'/>
        <see cref = 'Collector_submitBatches_Args'/>
        <see cref = 'Collector_submitBatches_Result'/>
        <see cref = 'Log'/>
        <see cref = 'Process'/>
        <see cref = 'Span'/>
        <see cref = 'SpanRef'/>
        <see cref = 'Tag'/>
    */
    public interface jaeger {
        // A trailing `// N:` on a field is its Thrift field id; `<field>_default` is the field's Thrift default.
        // Neither is read by AdHoc.
        // Thrift declares no size bounds. These permissive defaults replace AdHoc's 255 limit;
        // add [D(+N)] on a field whose real bound is known.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        // ═════════════════════════ jaeger.thrift ═════════════════════════

        /**
        TagType denotes the type of a Tag's value.
        */
        enum TagType {
            STRING = 0,
            DOUBLE = 1,
            BOOL = 2,
            LONG = 3,
            BINARY = 4,
        }

        enum SpanRefType {
            CHILD_OF = 0,
            FOLLOWS_FROM = 1,
        }

        /**
        Tag is a basic strongly typed key/value pair. It has been flattened to reduce the use of pointers in golang
        */
        public class Tag {
            string key; // 1:
            TagType vType; // 2:
            string vStr; // 3:
            double? vDouble; // 4:
            bool? vBool; // 5:
            [X] long? vLong; // 6:
            Binary[,,] vBinary; // 7:
        }

        /**
        Log is a timed even with an arbitrary set of tags.
        */
        public class Log {
            [X] long timestamp; // 1:
            Tag[,,] fields; // 2:
        }

        /**
        SpanRef describes causal relationship of the current span to another span (e.g. 'child-of')
        */
        public class SpanRef {
            SpanRefType refType; // 1:
            [X] long traceIdLow; // 2:
            [X] long traceIdHigh; // 3:
            [X] long spanId; // 4:
        }

        /**
        Span represents a named unit of work performed by a service.
        */
        public class Span {
            /**
            the least significant 64 bits of a traceID
            */
            [X] long traceIdLow; // 1:
            /**
            the most significant 64 bits of a traceID; 0 when only 64bit IDs are used
            */
            [X] long traceIdHigh; // 2:
            /**
            unique span id (only unique within a given trace)
            */
            [X] long spanId; // 3:
            /**
            since nearly all spans will have parents spans, CHILD_OF refs do not have to be explicit
            */
            [X] long parentSpanId; // 4:
            string operationName; // 5:
            /**
            causal references to other spans
            */
            SpanRef[,,] references; // 6:
            /**
            a bit field used to propagate sampling decisions. 1 signifies a SAMPLED span, 2 signifies a DEBUG span.
            */
            [X] int flags; // 7:
            [X] long startTime; // 8:
            [X] long duration; // 9:
            Tag[,,] tags; // 10:
            Log[,,] logs; // 11:
        }

        /**
        Process describes the traced process/service that emits spans.
        */
        public class Process {
            string serviceName; // 1:
            Tag[,,] tags; // 2:
        }

        /**
        ClientStats exposes some metrics from Jaeger client.
        Although Jaeger clients internally support integrations with metrics backends,
        not all users actually configure those, and even if they do, the metrics are
        often namespaced to the application, e.g. by including a tag service=xyz or
        using a custom prefix, which makes it more difficult to observe across the site.
        The ClientStats provides an alternative mechanism of reporting the same metrics
        to the Jaeger backend components (agent or collector) where those same metrics
        can be re-emitted with standardized naming scheme.
        */
        public class ClientStats {
            [X] long fullQueueDroppedSpans; // 1:
            [X] long tooLargeDroppedSpans; // 2:
            [X] long failedToEmitSpans; // 3:
        }

        /**
        Batch is a collection of spans reported out of process.
        */
        public class Batch {
            /**
            Since all spans submitted by a given client are produced by the same Process,
            it only needs to be sent once.
            */
            Process process; // 1:
            /**
            List of spans produced by a process. There is no specific limitation on the
            size of this list, however some transports may impose a cap on the total size
            of the overall Batch message, e.g. 65,000 bytes cap for UDP messages.
            */
            Span[,,] spans; // 2:
            /**
            Jaeger clients are encouraged to assign an incrementing sequence number to
            each batch, so that the Jaeger backend components could detect and report
            missing packets (especially when using the UDP transport).
            */
            [X] long? seqNo; // 3:
            ClientStats stats; // 4:
        }

        /**
        BatchSubmitResponse is the response on submitting a batch.
        */
        public class BatchSubmitResponse {
            /**
            The Collector's client is expected to only log (or emit a counter) when not ok equals false
            */
            bool ok; // 1:
        }

        // ───── packs of service Collector ─────

        /**
        Arguments of Collector.submitBatches().
        */
        public class Collector_submitBatches_Args {
            Batch[,,] batches; // 1:
        }

        /**
        Result of Collector.submitBatches().
        */
        public class Collector_submitBatches_Result {
            BatchSubmitResponse[,,] success; // 0:
        }

        // ═════════════════════════ topology ═════════════════════════

        // Calls the services (Left side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // Implements the services (Right side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface ClientServer : Connects<Client, Server> {

            /**
            Thrift service Collector
            */
            interface Collector {
                (L____________, Collector_submitBatches_Result) submitBatches(Collector_submitBatches_Args req);
            }
        }

        // ═════════════════════════ Thrift metadata attribute ═════════════════════════

        // Not read by AdHoc; kept so a Thrift annotation survives the conversion.

        /** Thrift annotation `(key = "value")` on the field or its type. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AnnotationAttribute : Attribute { public AnnotationAttribute(string key, string value) { } }
    }
}
