// Generated by Thrift2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: parquet.thrift
// parquet.thrift: namespace cpp parquet
// parquet.thrift: namespace java org.apache.parquet.format
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.thrift {
    /**
        <see cref = 'AesGcmCtrV1'/>
        <see cref = 'AesGcmV1'/>
        <see cref = 'BloomFilterAlgorithm'/>
        <see cref = 'BloomFilterCompression'/>
        <see cref = 'BloomFilterHash'/>
        <see cref = 'BloomFilterHeader'/>
        <see cref = 'BoundingBox'/>
        <see cref = 'BsonType'/>
        <see cref = 'ColumnChunk'/>
        <see cref = 'ColumnCryptoMetaData'/>
        <see cref = 'ColumnIndex'/>
        <see cref = 'ColumnMetaData'/>
        <see cref = 'ColumnOrder'/>
        <see cref = 'DataPageHeader'/>
        <see cref = 'DataPageHeaderV2'/>
        <see cref = 'DateType'/>
        <see cref = 'DecimalType'/>
        <see cref = 'DictionaryPageHeader'/>
        <see cref = 'EncryptionAlgorithm'/>
        <see cref = 'EncryptionWithColumnKey'/>
        <see cref = 'EncryptionWithFooterKey'/>
        <see cref = 'EnumType'/>
        <see cref = 'FileCryptoMetaData'/>
        <see cref = 'FileMetaData'/>
        <see cref = 'FileType'/>
        <see cref = 'Float16Type'/>
        <see cref = 'GeographyType'/>
        <see cref = 'GeometryType'/>
        <see cref = 'GeospatialStatistics'/>
        <see cref = 'IEEE754TotalOrder'/>
        <see cref = 'IndexPageHeader'/>
        <see cref = 'Int96TimestampOrder'/>
        <see cref = 'IntType'/>
        <see cref = 'JsonType'/>
        <see cref = 'KeyValue'/>
        <see cref = 'ListType'/>
        <see cref = 'LogicalType'/>
        <see cref = 'MapType'/>
        <see cref = 'MicroSeconds'/>
        <see cref = 'MilliSeconds'/>
        <see cref = 'NanoSeconds'/>
        <see cref = 'NullType'/>
        <see cref = 'OffsetIndex'/>
        <see cref = 'PageEncodingStats'/>
        <see cref = 'PageHeader'/>
        <see cref = 'PageLocation'/>
        <see cref = 'RowGroup'/>
        <see cref = 'SchemaElement'/>
        <see cref = 'SizeStatistics'/>
        <see cref = 'SortingColumn'/>
        <see cref = 'SplitBlockAlgorithm'/>
        <see cref = 'Statistics'/>
        <see cref = 'StringType'/>
        <see cref = 'TimeType'/>
        <see cref = 'TimeUnit'/>
        <see cref = 'TimestampType'/>
        <see cref = 'TypeDefinedOrder'/>
        <see cref = 'UUIDType'/>
        <see cref = 'Uncompressed'/>
        <see cref = 'VariantType'/>
        <see cref = 'XxHash'/>
    */
    public interface parquet {
        // A trailing `// N:` on a field is its Thrift field id; `<field>_default` is the field's Thrift default.
        // Neither is read by AdHoc.
        // Thrift declares no size bounds. These permissive defaults replace AdHoc's 255 limit;
        // add [D(+N)] on a field whose real bound is known.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        // ═════════════════════════ parquet.thrift ═════════════════════════

        /**
        Types supported by Parquet.  These types are intended to be used in combination
        with the encodings to control the on disk storage format.
        For example INT16 is not included as a type since a good encoding of INT32
        would handle this.
        */
        enum Type {
            BOOLEAN = 0,
            INT32 = 1,
            INT64 = 2,
            /**
            deprecated, new Parquet writers should not write data in INT96
            */
            INT96 = 3,
            FLOAT = 4,
            DOUBLE = 5,
            BYTE_ARRAY = 6,
            FIXED_LEN_BYTE_ARRAY = 7,
        }

        /**
        DEPRECATED: Common types used by frameworks (e.g. Hive, Pig) using parquet.
        ConvertedType is superseded by LogicalType.  This enum should not be extended.
        See LogicalTypes.md for conversion between ConvertedType and LogicalType.
        */
        enum ConvertedType {
            /**
            a BYTE_ARRAY actually contains UTF8 encoded chars
            */
            UTF8 = 0,
            /**
            a map is converted as an optional field containing a repeated key/value pair
            */
            MAP = 1,
            /**
            a key/value pair is converted into a group of two fields
            */
            MAP_KEY_VALUE = 2,
            /**
            a list is converted into an optional field containing a repeated field for its
            values
            */
            LIST = 3,
            /**
            an enum is converted into a BYTE_ARRAY field
            */
            ENUM = 4,
            /**
            A decimal value.
            This may be used to annotate BYTE_ARRAY or FIXED_LEN_BYTE_ARRAY primitive
            types. The underlying byte array stores the unscaled value encoded as two's
            complement using big-endian byte order (the most significant byte is the
            zeroth element). The value of the decimal is the value * 10^{-scale}.
            This must be accompanied by a (maximum) precision and a scale in the
            SchemaElement. The precision specifies the number of digits in the decimal
            and the scale stores the location of the decimal point. For example 1.23
            would have precision 3 (3 total digits) and scale 2 (the decimal point is
            2 digits over).
            */
            DECIMAL = 5,
            /**
            A Date
            Stored as days since Unix epoch, encoded as the INT32 physical type.
            */
            DATE = 6,
            /**
            A time
            The total number of milliseconds since midnight.  The value is stored
            as an INT32 physical type.
            */
            TIME_MILLIS = 7,
            /**
            A time.
            The total number of microseconds since midnight.  The value is stored as
            an INT64 physical type.
            */
            TIME_MICROS = 8,
            /**
            A date/time combination
            Date and time recorded as milliseconds since the Unix epoch.  Recorded as
            a physical type of INT64.
            */
            TIMESTAMP_MILLIS = 9,
            /**
            A date/time combination
            Date and time recorded as microseconds since the Unix epoch.  The value is
            stored as an INT64 physical type.
            */
            TIMESTAMP_MICROS = 10,
            /**
            An unsigned integer value.
            The number describes the maximum number of meaningful data bits in
            the stored value. 8, 16 and 32 bit values are stored using the
            INT32 physical type.  64 bit values are stored using the INT64
            physical type.
            */
            UINT_8 = 11,
            UINT_16 = 12,
            UINT_32 = 13,
            UINT_64 = 14,
            /**
            A signed integer value.
            The number describes the maximum number of meaningful data bits in
            the stored value. 8, 16 and 32 bit values are stored using the
            INT32 physical type.  64 bit values are stored using the INT64
            physical type.
            */
            INT_8 = 15,
            INT_16 = 16,
            INT_32 = 17,
            INT_64 = 18,
            /**
            An embedded JSON document
            A JSON document embedded within a single UTF8 column.
            */
            JSON = 19,
            /**
            An embedded BSON document
            A BSON document embedded within a single BYTE_ARRAY column.
            */
            BSON = 20,
            /**
            An interval of time
            This type annotates data stored as a FIXED_LEN_BYTE_ARRAY of length 12
            This data is composed of three separate little endian unsigned
            integers.  Each stores a component of a duration of time.  The first
            integer identifies the number of months associated with the duration,
            the second identifies the number of days associated with the duration
            and the third identifies the number of milliseconds associated with
            the provided duration.  This duration of time is independent of any
            particular timezone or date.
            */
            INTERVAL = 21,
        }

        /**
        Representation of Schemas
        */
        enum FieldRepetitionType {
            /**
            This field is required (can not be null) and each row has exactly 1 value.
            */
            REQUIRED = 0,
            /**
            The field is optional (can be null) and each row has 0 or 1 values.
            */
            OPTIONAL = 1,
            /**
            The field is repeated and can contain 0 or more values
            */
            REPEATED = 2,
        }

        /**
        Edge interpolation algorithm for Geography logical type
        */
        enum EdgeInterpolationAlgorithm {
            SPHERICAL = 0,
            VINCENTY = 1,
            THOMAS = 2,
            ANDOYER = 3,
            KARNEY = 4,
        }

        /**
        Encodings supported by Parquet.  Not all encodings are valid for all types.  These
        enums are also used to specify the encoding of definition and repetition levels.
        See the accompanying doc for the details of the more complicated encodings.
        */
        enum Encoding {
            /**
            Default encoding.
            BOOLEAN - 1 bit per value. 0 is false; 1 is true.
            INT32 - 4 bytes per value.  Stored as little-endian.
            INT64 - 8 bytes per value.  Stored as little-endian.
            FLOAT - 4 bytes per value.  IEEE. Stored as little-endian.
            DOUBLE - 8 bytes per value.  IEEE. Stored as little-endian.
            BYTE_ARRAY - 4 byte length stored as little endian, followed by bytes.
            FIXED_LEN_BYTE_ARRAY - Just the bytes.
            */
            PLAIN = 0,
            /**
            Group VarInt encoding for INT32/INT64.
            This encoding is deprecated. It was never used.
            GROUP_VAR_INT = 1;
            DEPRECATED: Dictionary encoding. The values in the dictionary are encoded in the
            plain type.
            For a data page use RLE_DICTIONARY instead.
            For a Dictionary page use PLAIN instead.
            */
            PLAIN_DICTIONARY = 2,
            /**
            Group packed run length encoding. Usable for definition/repetition levels
            encoding and Booleans (on one bit: 0 is false; 1 is true.)
            */
            RLE = 3,
            /**
            DEPRECATED: Bit packed encoding.  This can only be used if the data has a known max
            width.  Usable for definition/repetition levels encoding.
            Superseded by RLE (which is a hybrid of RLE and bit packing); see Encodings.md.
            */
            BIT_PACKED = 4,
            /**
            Delta encoding for integers. This can be used for int columns and works best
            on sorted data
            */
            DELTA_BINARY_PACKED = 5,
            /**
            Encoding for byte arrays to separate the length values and the data. The lengths
            are encoded using DELTA_BINARY_PACKED
            */
            DELTA_LENGTH_BYTE_ARRAY = 6,
            /**
            Incremental-encoded byte array. Prefix lengths are encoded using DELTA_BINARY_PACKED.
            Suffixes are stored as delta length byte arrays.
            */
            DELTA_BYTE_ARRAY = 7,
            /**
            Dictionary encoding: the ids are encoded using the RLE encoding
            */
            RLE_DICTIONARY = 8,
            /**
            Encoding for fixed-width data (FLOAT, DOUBLE, INT32, INT64, FIXED_LEN_BYTE_ARRAY).
            K byte-streams are created where K is the size in bytes of the data type.
            The individual bytes of a value are scattered to the corresponding stream and
            the streams are concatenated.
            This itself does not reduce the size of the data but can lead to better compression
            afterwards.
            Added in 2.8 for FLOAT and DOUBLE.
            Support for INT32, INT64 and FIXED_LEN_BYTE_ARRAY added in 2.11.
            */
            BYTE_STREAM_SPLIT = 9,
            /**
            Adaptive Lossless floating-Point (ALP) encoding for FLOAT and DOUBLE.
            Losslessly converts decimal-like floating-point values to integers via
            decimal scaling, then applies Frame of Reference (FOR) encoding and
            bit-packing; values that cannot be converted losslessly are stored as
            exceptions. See Encodings.md for the detailed specification.
            */
            ALP = 10,
        }

        /**
        Supported compression algorithms.
        Codecs added in format version X.Y can be read by readers based on X.Y and later.
        Codec support may vary between readers based on the format version and
        libraries available at runtime.
        See Compression.md for a detailed specification of these algorithms.
        */
        enum CompressionCodec {
            UNCOMPRESSED = 0,
            SNAPPY = 1,
            GZIP = 2,
            LZO = 3,
            /**
            Added in 2.4
            */
            BROTLI = 4,
            /**
            DEPRECATED (Added in 2.4)
            */
            LZ4 = 5,
            /**
            Added in 2.4
            */
            ZSTD = 6,
            /**
            Added in 2.9
            */
            LZ4_RAW = 7,
        }

        enum PageType {
            DATA_PAGE = 0,
            INDEX_PAGE = 1,
            DICTIONARY_PAGE = 2,
            DATA_PAGE_V2 = 3,
        }

        /**
        Enum to annotate whether lists of min/max elements inside ColumnIndex
        are ordered and if so, in which direction.
        */
        enum BoundaryOrder {
            UNORDERED = 0,
            ASCENDING = 1,
            DESCENDING = 2,
        }

        /**
        A structure for capturing metadata for estimating the unencoded,
        uncompressed size of data written. This is useful for readers to estimate
        how much memory is needed to reconstruct data in their memory model and for
        fine grained filter pushdown on nested structures (the histograms contained
        in this structure can help determine the number of nulls at a particular
        nesting level and maximum length of lists).
        */
        public class SizeStatistics {
            /**
            The number of physical bytes stored for BYTE_ARRAY data values assuming
            no encoding. This is exclusive of the bytes needed to store the length of
            each byte array. In other words, this field is equivalent to the `(size
            of PLAIN-ENCODING the byte array values) - (4 bytes * number of values
            written)`. To determine unencoded sizes of other types readers can use
            schema information multiplied by the number of non-null and null values.
            The number of null/non-null values can be inferred from the histograms
            below.
            For example, if a column chunk is dictionary-encoded with dictionary
            ["a", "bc", "cde"], and a data page contains the indices [0, 0, 1, 2],
            then this value for that data page should be 7 (1 + 1 + 2 + 3).
            This field should only be set for types that use BYTE_ARRAY as their
            physical type.
            */
            [X] long? unencoded_byte_array_data_bytes; // 1:
            /**
            When present, there is expected to be one element corresponding to each
            repetition (i.e. size=max repetition_level+1) where each element
            represents the number of times the repetition level was observed in the
            data.
            This field may be omitted if max_repetition_level is 0 without loss
            of information.
            */
            [X] long[,,] repetition_level_histogram; // 2:
            /**
            Same as repetition_level_histogram except for definition levels.
            This field may be omitted if max_definition_level is 0 or 1 without
            loss of information.
            */
            [X] long[,,] definition_level_histogram; // 3:
        }

        /**
        Bounding box for GEOMETRY or GEOGRAPHY type in the representation of min/max
        value pair of coordinates from each axis.
        */
        public class BoundingBox {
            double xmin; // 1:
            double xmax; // 2:
            double ymin; // 3:
            double ymax; // 4:
            double? zmin; // 5:
            double? zmax; // 6:
            double? mmin; // 7:
            double? mmax; // 8:
        }

        /**
        Statistics specific to Geometry and Geography logical types
        */
        public class GeospatialStatistics {
            /**
            A bounding box of geospatial instances
            */
            BoundingBox bbox; // 1:
            /**
            Geospatial type codes of all instances, or an empty list if not known
            */
            [X] int[,,] geospatial_types; // 2:
        }

        /**
        Statistics per row group and per page
        All fields are optional.
        */
        public class Statistics {
            /**
            DEPRECATED: min and max value of the column. Use min_value and max_value.
            Values are encoded using PLAIN encoding, except that variable-length byte
            arrays do not include a length prefix.
            These fields encode min and max values determined by signed comparison
            only. New files should use the correct order for a column's logical type
            and store the values in the min_value and max_value fields.
            To support older readers, these may be set when the column order is
            signed.
            */
            Binary[,,] max; // 1:
            Binary[,,] min; // 2:
            /**
            Count of null values in the column.
            Writers SHOULD always write this field even if it is zero (i.e. no null value)
            or the column is not nullable.
            Readers MUST distinguish between null_count not being present and null_count == 0.
            If null_count is not present, readers MUST NOT assume null_count == 0.
            */
            [X] long? null_count; // 3:
            /**
            count of distinct values occurring
            */
            [X] long? distinct_count; // 4:
            /**
            Lower and upper bound values for the column, determined by its ColumnOrder.
            These may be the actual minimum and maximum values found on a page or column
            chunk, but can also be (more compact) values that do not exist on a page or
            column chunk. For example, instead of storing "Blart Versenwald III", a writer
            may set min_value="B", max_value="C". Such more compact values must still be
            valid values within the column's logical type.
            Values are encoded using PLAIN encoding, except that variable-length byte
            arrays do not include a length prefix.
            */
            Binary[,,] max_value; // 5:
            Binary[,,] min_value; // 6:
            /**
            If true, max_value is the actual maximum value for a column
            */
            bool? is_max_value_exact; // 7:
            /**
            If true, min_value is the actual minimum value for a column
            */
            bool? is_min_value_exact; // 8:
            /**
            Count of NaN values in the column; only present if physical type is FLOAT
            or DOUBLE, or logical type is FLOAT16.
            If this field is not present, readers MUST assume NaNs may be present
            (i.e. MUST assume nan_count &gt; 0 and MAY NOT assume nan_count == 0).
            */
            [X] long? nan_count; // 9:
        }

        /**
        Empty structs to use as logical type annotations
        */
        public class StringType {
        }

        public class UUIDType {
        }

        public class MapType {
        }

        public class ListType {
        }

        public class EnumType {
        }

        public class DateType {
        }

        public class Float16Type {
        }

        /**
        Logical type to annotate a column that is always null.
        Sometimes when discovering the schema of existing data, values are always
        null and the physical type can't be determined. This annotation signals
        the case where the physical type was guessed from all null values.
        */
        public class NullType {
        }

        /**
        Decimal logical type annotation
        Scale must be zero or a positive integer less than or equal to the precision.
        Precision must be a non-zero positive integer.
        To maintain forward-compatibility in v1, implementations using this logical
        type must also set scale and precision on the annotated SchemaElement.
        Allowed for physical types: INT32, INT64, FIXED_LEN_BYTE_ARRAY, and BYTE_ARRAY.
        */
        public class DecimalType {
            [X] int scale; // 1:
            [X] int precision; // 2:
        }

        /**
        Time units for logical types
        */
        public class MilliSeconds {
        }

        public class MicroSeconds {
        }

        public class NanoSeconds {
        }

        /**
        Thrift union: exactly one of the fields is set.
        */
        public class TimeUnit {
            /**
            Thrift type MilliSeconds is an empty struct: carried as a bool presence flag.
            */
            bool? MILLIS; // 1:
            /**
            Thrift type MicroSeconds is an empty struct: carried as a bool presence flag.
            */
            bool? MICROS; // 2:
            /**
            Thrift type NanoSeconds is an empty struct: carried as a bool presence flag.
            */
            bool? NANOS; // 3:
        }

        /**
        Timestamp logical type annotation
        Allowed for physical types: INT64 and FIXED_LEN_BYTE_ARRAY with `type_length` = 12.
        */
        public class TimestampType {
            bool isAdjustedToUTC; // 1:
            TimeUnit unit; // 2:
        }

        /**
        Time logical type annotation
        Allowed for physical types: INT32 (millis), INT64 (micros, nanos)
        */
        public class TimeType {
            bool isAdjustedToUTC; // 1:
            TimeUnit unit; // 2:
        }

        /**
        Integer logical type annotation
        bitWidth must be 8, 16, 32, or 64.
        Allowed for physical types: INT32, INT64
        */
        public class IntType {
            sbyte bitWidth; // 1:
            bool isSigned; // 2:
        }

        /**
        Embedded JSON logical type annotation
        Allowed for physical types: BYTE_ARRAY
        */
        public class JsonType {
        }

        /**
        Embedded BSON logical type annotation
        Allowed for physical types: BYTE_ARRAY
        */
        public class BsonType {
        }

        /**
        Embedded Variant logical type annotation
        */
        public class VariantType {
            /**
            The version of the variant specification that the variant was
            written with.
            */
            sbyte? specification_version; // 1:
        }

        /**
        Embedded Geometry logical type annotation
        Geospatial features in the Well-Known Binary (WKB) format and `edges` interpolation
        is always linear/planar.
        A custom CRS can be set by the crs field. If unset, it defaults to "OGC:CRS84",
        which means that the geometries must be stored in longitude, latitude based on
        the WGS84 datum.
        Allowed for physical type: BYTE_ARRAY.
        See Geospatial.md for details.
        */
        public class GeometryType {
            string crs; // 1:
        }

        /**
        Embedded Geography logical type annotation
        Geospatial features in the WKB format with an explicit (non-linear/non-planar)
        `edges` interpolation algorithm.
        A custom geographic CRS can be set by the crs field, where longitudes are
        bound by [-180, 180] and latitudes are bound by [-90, 90]. If unset, the CRS
        defaults to "OGC:CRS84".
        An optional algorithm can be set to correctly interpret `edges` interpolation
        of the geometries. If unset, the algorithm defaults to SPHERICAL.
        Allowed for physical type: BYTE_ARRAY.
        See Geospatial.md for details.
        */
        public class GeographyType {
            string crs; // 1:
            EdgeInterpolationAlgorithm? algorithm; // 2:
        }

        /**
        File logical type annotation
        Annotates a group that represents a reference to a file, or to a range of
        bytes that may be stored inline or in an external file.
        See LogicalTypes.md for details.
        */
        public class FileType {
        }

        /**
        LogicalType annotations to replace ConvertedType.
        To maintain compatibility, implementations using LogicalType for a
        SchemaElement must also set the corresponding ConvertedType (if any)
        from the following table.
        Thrift union: exactly one of the fields is set.
        */
        public class LogicalType {
            /**
            use ConvertedType UTF8
            Thrift type StringType is an empty struct: carried as a bool presence flag.
            */
            bool? STRING; // 1:
            /**
            use ConvertedType MAP
            Thrift type MapType is an empty struct: carried as a bool presence flag.
            */
            bool? MAP; // 2:
            /**
            use ConvertedType LIST
            Thrift type ListType is an empty struct: carried as a bool presence flag.
            */
            bool? LIST; // 3:
            /**
            use ConvertedType ENUM
            Thrift type EnumType is an empty struct: carried as a bool presence flag.
            */
            bool? ENUM; // 4:
            /**
            use ConvertedType DECIMAL + SchemaElement.{scale, precision}
            */
            DecimalType DECIMAL; // 5:
            /**
            use ConvertedType DATE
            Thrift type DateType is an empty struct: carried as a bool presence flag.
            */
            bool? DATE; // 6:
            /**
            use ConvertedType TIME_MICROS for TIME(isAdjustedToUTC = *, unit = MICROS)
            use ConvertedType TIME_MILLIS for TIME(isAdjustedToUTC = *, unit = MILLIS)
            */
            TimeType TIME; // 7:
            /**
            use ConvertedType TIMESTAMP_MICROS for TIMESTAMP(isAdjustedToUTC = *, unit = MICROS)
            use ConvertedType TIMESTAMP_MILLIS for TIMESTAMP(isAdjustedToUTC = *, unit = MILLIS)
            */
            TimestampType TIMESTAMP; // 8:
            /**
            9: reserved for INTERVAL
            use ConvertedType INT_* or UINT_*
            */
            IntType INTEGER; // 10:
            /**
            no compatible ConvertedType
            Thrift type NullType is an empty struct: carried as a bool presence flag.
            */
            bool? UNKNOWN; // 11:
            /**
            use ConvertedType JSON
            Thrift type JsonType is an empty struct: carried as a bool presence flag.
            */
            bool? JSON; // 12:
            /**
            use ConvertedType BSON
            Thrift type BsonType is an empty struct: carried as a bool presence flag.
            */
            bool? BSON; // 13:
            /**
            no compatible ConvertedType
            Thrift type UUIDType is an empty struct: carried as a bool presence flag.
            */
            bool? UUID; // 14:
            /**
            no compatible ConvertedType
            Thrift type Float16Type is an empty struct: carried as a bool presence flag.
            */
            bool? FLOAT16; // 15:
            /**
            no compatible ConvertedType
            */
            VariantType VARIANT; // 16:
            /**
            no compatible ConvertedType
            */
            GeometryType GEOMETRY; // 17:
            /**
            no compatible ConvertedType
            */
            GeographyType GEOGRAPHY; // 18:
            /**
            no compatible ConvertedType
            Thrift type FileType is an empty struct: carried as a bool presence flag.
            */
            bool? FILE; // 19:
        }

        /**
        Represents an element inside a schema definition.
        - if it is a group (inner node) then type is undefined and num_children is defined
        - if it is a primitive type (leaf) then type is defined and num_children is undefined
        the nodes are listed in depth first traversal order.
        */
        public class SchemaElement {
            /**
            Data type for this field. Not set if the current element is a non-leaf node
            */
            Type? Type; // 1:
            /**
            If type is FIXED_LEN_BYTE_ARRAY, this is the byte length of the values.
            Otherwise, if specified, this is the maximum bit length to store any of the values.
            (e.g. a low cardinality INT col could have this set to 3).  Note that this is
            in the schema, and therefore fixed for the entire file.
            */
            [X] int? type_length; // 2:
            /**
            repetition of the field. The root of the schema does not have a repetition_type.
            All other nodes must have one
            */
            FieldRepetitionType? repetition_type; // 3:
            /**
            Name of the field in the schema
            */
            string name; // 4:
            /**
            Nested fields.  Since thrift does not support nested fields,
            the nesting is flattened to a single list by a depth-first traversal.
            The children count is used to construct the nested relationship.
            This field is not set when the element is a primitive type
            */
            [X] int? num_children; // 5:
            /**
            DEPRECATED: When the schema is the result of a conversion from another model.
            Used to record the original type to help with cross conversion.
            This is superseded by logicalType.
            */
            ConvertedType? converted_type; // 6:
            /**
            DEPRECATED: Used when this column contains decimal data.
            See the DECIMAL converted type for more details.
            This is superseded by using the DecimalType annotation in logicalType.
            */
            [X] int? scale; // 7:
            [X] int? precision; // 8:
            /**
            When the original schema supports field ids, this will save the
            original field id in the parquet schema
            */
            [X] int? field_id; // 9:
            /**
            The logical type of this SchemaElement
            LogicalType replaces ConvertedType, but ConvertedType is still required
            for some logical types to ensure forward-compatibility in format v1.
            */
            LogicalType logicalType; // 10:
        }

        /**
        Data page header
        */
        public class DataPageHeader {
            /**
            Number of values, including NULLs, in this data page.
            If an OffsetIndex is present, a page must begin at a row
            boundary (repetition_level = 0). Otherwise, pages may begin
            within a row (repetition_level &gt; 0).
            */
            [X] int num_values; // 1:
            /**
            Encoding used for this data page *
            */
            Encoding encoding; // 2:
            /**
            Encoding used for definition levels *
            */
            Encoding definition_level_encoding; // 3:
            /**
            Encoding used for repetition levels *
            */
            Encoding repetition_level_encoding; // 4:
            /**
            Optional statistics for the data in this page *
            */
            Statistics statistics; // 5:
        }

        public class IndexPageHeader {
        }

        /**
        The dictionary page must be placed at the first position of the column chunk
        if it is partly or completely dictionary encoded. At most one dictionary page
        can be placed in a column chunk.
        */
        public class DictionaryPageHeader {
            /**
            Number of values in the dictionary *
            */
            [X] int num_values; // 1:
            /**
            Encoding using this dictionary page *
            */
            Encoding encoding; // 2:
            /**
            If true, the entries in the dictionary are sorted in ascending order *
            */
            bool? is_sorted; // 3:
        }

        /**
        Alternate page format allowing reading levels without decompressing the data
        Repetition and definition levels are uncompressed
        The remaining section containing the data is compressed if is_compressed is true
        Implementation note - this header is not necessarily a strict improvement over
        `DataPageHeader` (in particular the original header might provide better compression
        in some scenarios). Page indexes require pages to start and end at row boundaries,
        regardless of which page header is used.
        */
        public class DataPageHeaderV2 {
            /**
            Number of values, including NULLs, in this data page. *
            */
            [X] int num_values; // 1:
            /**
            Number of NULL values, in this data page.
            Number of non-null = num_values - num_nulls which is also the number of values in the data section *
            */
            [X] int num_nulls; // 2:
            /**
            Number of rows in this data page. Every page must begin at a
            row boundary (repetition_level = 0): rows must **not** be
            split across page boundaries when using V2 data pages.
            */
            [X] int num_rows; // 3:
            /**
            Encoding used for data in this page *
            */
            Encoding encoding; // 4:
            /**
            repetition levels and definition levels are always using RLE (without size in it)
            Length of the definition levels
            */
            [X] int definition_levels_byte_length; // 5:
            /**
            Length of the repetition levels
            */
            [X] int repetition_levels_byte_length; // 6:
            /**
            Whether the values are compressed.
            Which means the section of the page between
            definition_levels_byte_length + repetition_levels_byte_length and compressed_page_size (included)
            is compressed with the compression_codec.
            If missing it is considered compressed
            */
            bool? is_compressed; // 7:
            public const bool is_compressed_default = true;
            /**
            Optional statistics for the data in this page *
            */
            Statistics statistics; // 8:
        }

        /**
        Block-based algorithm type annotation. *
        */
        public class SplitBlockAlgorithm {
        }

        /**
        The algorithm used in Bloom filter. *
        Thrift union: exactly one of the fields is set.
        */
        public class BloomFilterAlgorithm {
            /**
            Block-based Bloom filter. *
            Thrift type SplitBlockAlgorithm is an empty struct: carried as a bool presence flag.
            */
            bool? BLOCK; // 1:
        }

        /**
        Hash strategy type annotation. xxHash is an extremely fast non-cryptographic hash
        algorithm. It uses 64 bits version of xxHash.
        */
        public class XxHash {
        }

        /**
        The hash function used in Bloom filter. This function takes the hash of a column value
        using plain encoding.
        Thrift union: exactly one of the fields is set.
        */
        public class BloomFilterHash {
            /**
            xxHash Strategy. *
            Thrift type XxHash is an empty struct: carried as a bool presence flag.
            */
            bool? XXHASH; // 1:
        }

        /**
        The compression used in the Bloom filter.
        */
        public class Uncompressed {
        }

        /**
        Thrift union: exactly one of the fields is set.
        */
        public class BloomFilterCompression {
            /**
            Thrift type Uncompressed is an empty struct: carried as a bool presence flag.
            */
            bool? UNCOMPRESSED; // 1:
        }

        /**
        Bloom filter header is stored at beginning of Bloom filter data of each column
        and followed by its bitset.
        */
        public class BloomFilterHeader {
            /**
            The size of bitset in bytes *
            */
            [X] int numBytes; // 1:
            /**
            The algorithm for setting bits. *
            */
            BloomFilterAlgorithm algorithm; // 2:
            /**
            The hash function used for Bloom filter. *
            */
            BloomFilterHash hash; // 3:
            /**
            The compression used in the Bloom filter *
            */
            BloomFilterCompression compression; // 4:
        }

        public class PageHeader {
            /**
            the type of the page: indicates which of the *_header fields is set *
            */
            PageType Type; // 1:
            /**
            Uncompressed page size in bytes (not including this header) *
            */
            [X] int uncompressed_page_size; // 2:
            /**
            Compressed (and potentially encrypted) page size in bytes, not including this header *
            */
            [X] int compressed_page_size; // 3:
            /**
            The 32-bit CRC checksum for the page, to be calculated as follows:
            - The standard CRC32 algorithm is used (with polynomial 0x04C11DB7,
            the same as in e.g. GZIP).
            - All page types can have a CRC (v1 and v2 data pages, dictionary pages,
            etc.).
            - The CRC is computed on the serialization binary representation of the page
            (as written to disk), excluding the page header. For example, for v1
            data pages, the CRC is computed on the concatenation of repetition levels,
            definition levels and column values (optionally compressed, optionally
            encrypted).
            - The CRC computation therefore takes place after any compression
            and encryption steps, if any.
            If enabled, this allows for disabling checksumming in HDFS if only a few
            pages need to be read.
            */
            [X] int? crc; // 4:
            /**
            Headers for page specific data.  One only will be set.
            */
            DataPageHeader data_page_header; // 5:
            /**
            Thrift type IndexPageHeader is an empty struct: carried as a bool presence flag.
            */
            bool? index_page_header; // 6:
            DictionaryPageHeader dictionary_page_header; // 7:
            DataPageHeaderV2 data_page_header_v2; // 8:
        }

        /**
        Wrapper struct to store key values
        */
        public class KeyValue {
            string key; // 1:
            string value; // 2:
        }

        /**
        Sort order within a RowGroup of a leaf column
        */
        public class SortingColumn {
            /**
            The ordinal position of the column (in this row group) *
            */
            [X] int column_idx; // 1:
            /**
            If true, indicates this column is sorted in descending order. *
            */
            bool descending; // 2:
            /**
            If true, nulls will come before non-null values, otherwise,
            nulls go at the end.
            */
            bool nulls_first; // 3:
        }

        /**
        statistics of a given page type and encoding
        */
        public class PageEncodingStats {
            /**
            the page type (data/dic/...) *
            */
            PageType page_type; // 1:
            /**
            encoding of the page *
            */
            Encoding encoding; // 2:
            /**
            number of pages of this type with this encoding *
            */
            [X] int count; // 3:
        }

        /**
        Description for column metadata
        */
        public class ColumnMetaData {
            /**
            Type of this column *
            */
            Type Type; // 1:
            /**
            Set of all encodings used for this column. The purpose is to validate
            whether we can decode those pages. *
            */
            Encoding[,,] encodings; // 2:
            /**
            Path in schema *
            */
            string[,,] path_in_schema; // 3:
            /**
            Compression codec *
            */
            CompressionCodec codec; // 4:
            /**
            Number of values in this column *
            */
            [X] long num_values; // 5:
            /**
            total byte size of all uncompressed pages in this column chunk (including the headers) *
            */
            [X] long total_uncompressed_size; // 6:
            /**
            total byte size of all compressed, and potentially encrypted, pages
            in this column chunk (including the headers) *
            */
            [X] long total_compressed_size; // 7:
            /**
            Optional key/value metadata *
            */
            KeyValue[,,] key_value_metadata; // 8:
            /**
            Byte offset from beginning of file to first data page *
            */
            [X] long data_page_offset; // 9:
            /**
            Byte offset from beginning of file to root index page *
            */
            [X] long? index_page_offset; // 10:
            /**
            Byte offset from the beginning of file to first (only) dictionary page *
            */
            [X] long? dictionary_page_offset; // 11:
            /**
            optional statistics for this column chunk
            */
            Statistics statistics; // 12:
            /**
            Set of all encodings used for pages in this column chunk.
            This information can be used to determine if all data pages are
            dictionary encoded for example *
            */
            PageEncodingStats[,,] encoding_stats; // 13:
            /**
            Byte offset from beginning of file to Bloom filter data. *
            */
            [X] long? bloom_filter_offset; // 14:
            /**
            Size of Bloom filter data including the serialized header, in bytes.
            Added in 2.10 so readers may not read this field from old files and
            it can be obtained after the BloomFilterHeader has been deserialized.
            Writers should write this field so readers can read the bloom filter
            in a single I/O.
            */
            [X] int? bloom_filter_length; // 15:
            /**
            Optional statistics to help estimate total memory when converted to in-memory
            representations. The histograms contained in these statistics can
            also be useful in some cases for more fine-grained nullability/list length
            filter pushdown.
            */
            SizeStatistics size_statistics; // 16:
            /**
            Optional statistics specific for Geometry and Geography logical types
            */
            GeospatialStatistics geospatial_statistics; // 17:
        }

        public class EncryptionWithFooterKey {
        }

        public class EncryptionWithColumnKey {
            /**
            Column path in schema *
            */
            string[,,] path_in_schema; // 1:
            /**
            Retrieval metadata of column encryption key *
            */
            Binary[,,] key_metadata; // 2:
        }

        /**
        Thrift union: exactly one of the fields is set.
        */
        public class ColumnCryptoMetaData {
            /**
            Thrift type EncryptionWithFooterKey is an empty struct: carried as a bool presence flag.
            */
            bool? ENCRYPTION_WITH_FOOTER_KEY; // 1:
            EncryptionWithColumnKey ENCRYPTION_WITH_COLUMN_KEY; // 2:
        }

        public class ColumnChunk {
            /**
            File where column data is stored.  If not set, assumed to be same file as
            metadata.  This path is relative to the current file.
            As of December 2025, the only known use-case for this field is writing summary
            parquet files (i.e. "_metadata" files).  These files consolidate footers from
            multiple parquet files to allow for efficient reading of footers to avoid file
            listing costs and prune out files that do not need to be read based on statistics.
            These files do not appear to have ever been formally specified in the specification.
            and are potentially problematic from a correctness perspective [1].
            [1] https://lists.apache.org/thread/ootf2kmyg3p01b1bvplpvp4ftd1bt72d
            There is no other known usage of this field. Specifically, there are no known
            reference implementations that will read externally stored column data if this field is populated
            within a standard parquet file. Making use of the field for this purpose is
            not considered part of the Parquet specification.
            */
            string file_path; // 1:
            /**
            DEPRECATED: Byte offset in file_path to the ColumnMetaData
            Past use of this field has been inconsistent, with some implementations
            using it to point to the ColumnMetaData and some using it to point to
            the first page in the column chunk. In many cases, the ColumnMetaData at this
            location is wrong. This field is now deprecated and should not be used.
            Writers should set this field to 0 if no ColumnMetaData has been written outside
            the footer.
            */
            [X] long file_offset; // 2:
            public const long file_offset_default = 0;
            /**
            Column metadata for this chunk. Some writers may also replicate this at the
            location pointed to by file_path/file_offset.
            Note: while marked as optional, this field is in fact required by most major
            Parquet implementations. As such, writers MUST populate this field.
            */
            ColumnMetaData meta_data; // 3:
            /**
            File offset of ColumnChunk's OffsetIndex *
            */
            [X] long? offset_index_offset; // 4:
            /**
            Size of ColumnChunk's OffsetIndex, in bytes *
            */
            [X] int? offset_index_length; // 5:
            /**
            File offset of ColumnChunk's ColumnIndex *
            */
            [X] long? column_index_offset; // 6:
            /**
            Size of ColumnChunk's ColumnIndex, in bytes *
            */
            [X] int? column_index_length; // 7:
            /**
            Crypto metadata of encrypted columns *
            */
            ColumnCryptoMetaData crypto_metadata; // 8:
            /**
            Encrypted column metadata for this chunk *
            */
            Binary[,,] encrypted_column_metadata; // 9:
        }

        public class RowGroup {
            /**
            Metadata for each column chunk in this row group.
            This list must have the same order as the SchemaElement list in FileMetaData.
            */
            ColumnChunk[,,] columns; // 1:
            /**
            Total byte size of all the uncompressed column data in this row group *
            */
            [X] long total_byte_size; // 2:
            /**
            Number of rows in this row group *
            */
            [X] long num_rows; // 3:
            /**
            If set, specifies a sort ordering of the rows in this RowGroup.
            The sorting columns can be a subset of all the columns.
            */
            SortingColumn[,,] sorting_columns; // 4:
            /**
            Byte offset from beginning of file to first page (data or dictionary)
            in this row group *
            */
            [X] long? file_offset; // 5:
            /**
            Total byte size of all compressed (and potentially encrypted) column data
            in this row group *
            */
            [X] long? total_compressed_size; // 6:
            /**
            Row group ordinal in the file *
            */
            [X] short? ordinal; // 7:
        }

        /**
        Empty struct to signal the order defined by the physical or logical type
        */
        public class TypeDefinedOrder {
        }

        /**
        Empty struct to signal IEEE 754 total order for floating point types
        */
        public class IEEE754TotalOrder {
        }

        /**
        Empty struct to signal chronological ordering of physical type INT96
        */
        public class Int96TimestampOrder {
        }

        /**
        Union to specify the order used for the min_value and max_value fields for a
        column. This union takes the role of an enhanced enum that allows rich
        elements (which will be needed for a collation-based ordering in the future).
        Possible values are:
        * TypeDefinedOrder - the column uses the order defined by its logical or
        physical type (if there is no logical type).
        * IEEE754TotalOrder - the floating point column uses IEEE 754 total order.
        * Int96TimestampOrder - the INT96 column uses chronological timestamp order.
        If the reader does not support the value of this union, min and max stats
        for this column should be ignored.
        Thrift union: exactly one of the fields is set.
        */
        public class ColumnOrder {
            /**
            The sort orders for logical types are:
            UTF8 - unsigned byte-wise comparison
            INT8 - signed comparison
            INT16 - signed comparison
            INT32 - signed comparison
            INT64 - signed comparison
            UINT8 - unsigned comparison
            UINT16 - unsigned comparison
            UINT32 - unsigned comparison
            UINT64 - unsigned comparison
            DECIMAL - signed comparison of the represented value
            DATE - signed comparison
            FLOAT16 - signed comparison of the represented value (*)
            TIME_MILLIS - signed comparison
            TIME_MICROS - signed comparison
            TIMESTAMP_MILLIS - signed comparison
            TIMESTAMP_MICROS - signed comparison
            INTERVAL - undefined
            JSON - unsigned byte-wise comparison
            BSON - unsigned byte-wise comparison
            ENUM - unsigned byte-wise comparison
            LIST - undefined
            MAP - undefined
            VARIANT - undefined
            GEOMETRY - undefined
            GEOGRAPHY - undefined
            FILE - undefined
            In the absence of logical types, the sort order is determined by the physical type:
            BOOLEAN - false, true
            INT32 - signed comparison
            INT64 - signed comparison
            INT96 (only used for legacy timestamps) - depends on sort order (+)
            FLOAT - signed comparison of the represented value (*)
            DOUBLE - signed comparison of the represented value (*)
            BYTE_ARRAY - unsigned byte-wise comparison
            FIXED_LEN_BYTE_ARRAY - unsigned byte-wise comparison
            (+) While the INT96 type has been deprecated, at the time of writing it is
            still used in many legacy systems. It is optional for writers to emit
            statistics for INT96 columns. Writers that emit stats for such columns
            should use the INT96_TIMESTAMP_ORDER for this type and order the values
            according to the legacy rules:
            - compare the last 4 bytes (days) as a little-endian 32-bit signed integer
            - if equal last 4 bytes, compare the first 8 bytes as a little-endian
            64-bit signed integer (nanos)
            If TYPE_ORDER is used for an INT96 column, readers should ignore all statistics
            (`min`/`max` fields in `Statistics` and `min_values`/`max_values` fields in
            `ColumnIndex`) for that column.
            (*) Because TYPE_ORDER is ambiguous for floating point types due to
            underspecified handling of NaN and -0/+0, it is recommended that writers
            use IEEE_754_TOTAL_ORDER for these types.
            If TYPE_ORDER is used for floating point types, then the following
            compatibility rules should be applied when reading statistics:
            - If the min is a NaN, it should be ignored.
            - If the max is a NaN, it should be ignored.
            - If the nan_count field is set, a reader can compute
            nan_count + null_count == num_values to deduce whether all non-null
            values are NaN.
            - If the min is +0, the row group may contain -0 values as well.
            - If the max is -0, the row group may contain +0 values as well.
            - When looking for NaN values, min and max should be ignored.
            If the nan_count field is set, it can be used to check whether
            NaNs are present.
            When writing page or column chunk statistics for columns with
            TYPE_ORDER order, the following rules must be followed:
            - The nan_count field must be set for floating point types, even if
            it is zero.
            - If the nan_count field is set, min and max statistics fields, when
            present, must not contain NaN values and must be computed from
            non-NaN values only. This signals to readers that the min and max
            statistics are reliable for non-NaN values.
            - If all non-null values are NaN, min and max statistics must not be
            written.
            - If the computed max value is zero (whether negative or positive),
            `+0.0` should be written into the max statistics field.
            - If the computed min value is zero (whether negative or positive),
            `-0.0` should be written into the min statistics field.
            When writing column indexes for columns with TYPE_ORDER order, the
            following rules must be followed:
            - NaNs must not be written to min_values or max_values.
            - If all non-null values of a page are NaN, a column index must not
            be written for this column chunk because min_values and max_values
            are required.
            - If the computed max value is zero (whether negative or positive),
            `+0.0` should be written into the corresponding max_values entry.
            - If the computed min value is zero (whether negative or positive),
            `-0.0` should be written into the corresponding min_values entry.
            Thrift type TypeDefinedOrder is an empty struct: carried as a bool presence flag.
            */
            bool? TYPE_ORDER; // 1:
            /**
            Thrift type IEEE754TotalOrder is an empty struct: carried as a bool presence flag.
            */
            bool? IEEE_754_TOTAL_ORDER; // 2:
            /**
            Thrift type Int96TimestampOrder is an empty struct: carried as a bool presence flag.
            */
            bool? INT96_TIMESTAMP_ORDER; // 3:
        }

        public class PageLocation {
            /**
            Offset of the page in the file *
            */
            [X] long offset; // 1:
            /**
            Size of the page, including header. Equal to the sum of the page's
            PageHeader.compressed_page_size and the size of the serialized PageHeader.
            */
            [X] int compressed_page_size; // 2:
            /**
            Index within the RowGroup of the first row of the page. When an
            OffsetIndex is present, pages must begin on row boundaries
            (repetition_level = 0).
            */
            [X] long first_row_index; // 3:
        }

        /**
        Optional offsets for each data page in a ColumnChunk.
        Forms part of the page index, along with ColumnIndex.
        OffsetIndex may be present even if ColumnIndex is not.
        */
        public class OffsetIndex {
            /**
            PageLocations, ordered by increasing PageLocation.offset. It is required
            that page_locations[i].first_row_index &lt; page_locations[i+1].first_row_index.
            */
            PageLocation[,,] page_locations; // 1:
            /**
            Unencoded/uncompressed size for BYTE_ARRAY types.
            See documentation for unencoded_byte_array_data_bytes in SizeStatistics for
            more details on this field.
            */
            [X] long[,,] unencoded_byte_array_data_bytes; // 2:
        }

        /**
        Optional statistics for each data page in a ColumnChunk.
        Forms part the page index, along with OffsetIndex.
        If this structure is present, OffsetIndex must also be present.
        For each field in this structure, &lt;field&gt;[i] refers to the page at
        OffsetIndex.page_locations[i]
        */
        public class ColumnIndex {
            /**
            A list of Boolean values to determine the validity of the corresponding
            min and max values. If true, a page contains only null values, and writers
            have to set the corresponding entries in min_values and max_values to
            byte[0], so that all lists have the same length. If false, the
            corresponding entries in min_values and max_values must be valid.
            */
            bool[,,] null_pages; // 1:
            /**
            Two lists containing lower and upper bounds for the values of each page
            determined by the ColumnOrder of the column. These may be the actual
            minimum and maximum values found on a page, but can also be (more compact)
            values that do not exist on a page. For example, instead of storing "Blart
            Versenwald III", a writer may set min_values[i]="B", max_values[i]="C".
            Such more compact values must still be valid values within the column's
            logical type. Readers must make sure that list entries are populated before
            using them by inspecting null_pages.
            For columns of physical type FLOAT or DOUBLE, or logical type FLOAT16,
            NaN values are not to be included in these bounds. If all non-null values
            of a page are NaN, then a writer must do the following:
            - If the order of this column is TYPE_ORDER, then a column index must
            not be written for this column chunk. While this is unfortunate for
            performance, it is necessary to avoid conflict with legacy files that
            still included NaN in min_values and max_values even if the page had
            non-NaN values. To mitigate this, IEEE754_TOTAL_ORDER is recommended.
            - If the order of this column is IEEE754_TOTAL_ORDER, then min_values[i]
            and max_values[i] of that page must be set to the smallest and largest
            NaN values as defined by IEEE 754 total order.
            For columns of physical type INT96, the writer must do the following:
            - If the order of this column is not INT96_TIMESTAMP_ORDER, then a column
            index must not be written for this column chunk.
            - If the order of this column is INT96_TIMESTAMP_ORDER, the min_values[i]
            and max_values[i] of that page must be set to the smallest and largest
            values as defined by the INT96 chronological timestamp ordering.
            */
            Binary[,,][,,] min_values; // 2:
            Binary[,,][,,] max_values; // 3:
            /**
            Stores whether both min_values and max_values are ordered and if so, in
            which direction. This allows readers to perform binary searches in both
            lists. Readers cannot assume that max_values[i] &lt;= min_values[i+1], even
            if the lists are ordered.
            */
            BoundaryOrder boundary_order; // 4:
            /**
            A list containing the number of null values for each page
            Writers SHOULD always write this field even if no null values
            are present or the column is not nullable.
            Readers MUST distinguish between null_counts not being present
            and null_count being 0.
            If null_counts are not present, readers MUST NOT assume all
            null counts are 0.
            */
            [X] long[,,] null_counts; // 5:
            /**
            Contains repetition level histograms for each page
            concatenated together.  The repetition_level_histogram field on
            SizeStatistics contains more details.
            When present the length should always be (number of pages *
            (max_repetition_level + 1)) elements.
            Element 0 is the first element of the histogram for the first page.
            Element (max_repetition_level + 1) is the first element of the histogram
            for the second page.
            */
            [X] long[,,] repetition_level_histograms; // 6:
            /**
            Same as repetition_level_histograms except for definitions levels.
            */
            [X] long[,,] definition_level_histograms; // 7:
            /**
            A list containing the number of NaN values for each page. Only present
            for columns of physical type FLOAT or DOUBLE, or logical type FLOAT16.
            If this field is not present, readers MUST assume that there might be
            NaN values in any page.
            */
            [X] long[,,] nan_counts; // 8:
        }

        public class AesGcmV1 {
            /**
            AAD prefix *
            */
            Binary[,,] aad_prefix; // 1:
            /**
            Unique file identifier part of AAD suffix *
            */
            Binary[,,] aad_file_unique; // 2:
            /**
            In files encrypted with AAD prefix without storing it,
            readers must supply the prefix *
            */
            bool? supply_aad_prefix; // 3:
        }

        public class AesGcmCtrV1 {
            /**
            AAD prefix *
            */
            Binary[,,] aad_prefix; // 1:
            /**
            Unique file identifier part of AAD suffix *
            */
            Binary[,,] aad_file_unique; // 2:
            /**
            In files encrypted with AAD prefix without storing it,
            readers must supply the prefix *
            */
            bool? supply_aad_prefix; // 3:
        }

        /**
        Thrift union: exactly one of the fields is set.
        */
        public class EncryptionAlgorithm {
            AesGcmV1 AES_GCM_V1; // 1:
            AesGcmCtrV1 AES_GCM_CTR_V1; // 2:
        }

        /**
        Description for file metadata
        */
        public class FileMetaData {
            /**
            Version of this file
            As of December 2025, there is no agreed upon consensus of what constitutes
            version 2 of the file. For maximum compatibility with readers, writers should
            always populate "1" for version. For maximum compatibility with writers,
            readers should accept "1" and "2" interchangeably.  All other versions are
            reserved for potential future use-cases.
            */
            [X] int version; // 1:
            /**
            Parquet schema for this file.  This schema contains metadata for all the columns.
            The schema is represented as a tree with a single root.  The nodes of the tree
            are flattened to a list by doing a depth-first traversal.
            The column metadata contains the path in the schema for that column which can be
            used to map columns to nodes in the schema.
            The first element is the root *
            */
            SchemaElement[,,] schema; // 2:
            /**
            Number of rows in this file *
            */
            [X] long num_rows; // 3:
            /**
            Row groups in this file *
            */
            RowGroup[,,] row_groups; // 4:
            /**
            Optional key/value metadata *
            */
            KeyValue[,,] key_value_metadata; // 5:
            /**
            String for application that wrote this file.  This should be in the format
            &lt;Application&gt; version &lt;App Version&gt; (build &lt;App Build Hash&gt;).
            e.g. impala version 1.0 (build 6cf94d29b2b7115df4de2c06e2ab4326d721eb55)
            */
            string created_by; // 6:
            /**
            Sort order used for the min_value and max_value fields in the Statistics
            objects and the min_values and max_values fields in the ColumnIndex
            objects of each column in this file. Sort orders are listed in the order
            matching the columns in the schema. The indexes are not necessarily the same
            though, because only leaf nodes of the schema are represented in the list
            of sort orders.
            Without column_orders, the meaning of the min_value and max_value fields
            in the Statistics object and the ColumnIndex object is undefined. To ensure
            well-defined behaviour, if these fields are written to a Parquet file,
            column_orders must be written as well.
            The obsolete min and max fields in the Statistics object are always sorted
            by signed comparison regardless of column_orders.
            */
            ColumnOrder[,,] column_orders; // 7:
            /**
            Encryption algorithm. This field is set only in encrypted files
            with plaintext footer. Files with encrypted footer store algorithm id
            in FileCryptoMetaData structure.
            */
            EncryptionAlgorithm encryption_algorithm; // 8:
            /**
            Retrieval metadata of key used for signing the footer.
            Used only in encrypted files with plaintext footer.
            */
            Binary[,,] footer_signing_key_metadata; // 9:
        }

        /**
        Crypto metadata for files with encrypted footer *
        */
        public class FileCryptoMetaData {
            /**
            Encryption algorithm. This field is only used for files
            with encrypted footer. Files with plaintext footer store algorithm id
            inside footer (FileMetaData structure).
            */
            EncryptionAlgorithm encryption_algorithm; // 1:
            /**
            Retrieval metadata of key used for encryption of footer,
            and (possibly) columns *
            */
            Binary[,,] key_metadata; // 2:
        }

        // ═════════════════════════ topology ═════════════════════════

        // Calls the services (Left side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // Implements the services (Right side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        // No services in the source: every pack may be sent by either side.
        interface ClientServer : Connects<Client, Server> {
            // Every pack of the project, in both directions; the FSM never transitions.
            // SkipName keeps the metadata attribute classes declared in this interface out of the pack set.
            [_____lr_____<@parquet>(SkipName: @"Attribute$")]
            struct Start { }
        }

        // ═════════════════════════ Thrift metadata attribute ═════════════════════════

        // Not read by AdHoc; kept so a Thrift annotation survives the conversion.

        /** Thrift annotation `(key = "value")` on the field or its type. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AnnotationAttribute : Attribute { public AnnotationAttribute(string key, string value) { } }
    }
}
