// Generated by Thrift2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: shared.thrift
// shared.thrift: namespace cl shared
// shared.thrift: namespace cpp shared
// shared.thrift: namespace d share
// shared.thrift: namespace dart shared
// shared.thrift: namespace java shared
// shared.thrift: namespace perl shared
// shared.thrift: namespace php shared
// shared.thrift: namespace haxe shared
// shared.thrift: namespace netstd shared
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.thrift {
    /**
        <see cref = 'SharedService_getStruct_Args'/>
        <see cref = 'SharedService_getStruct_Result'/>
        <see cref = 'SharedStruct'/>
    */
    public interface shared {
        // A trailing `// N:` on a field is its Thrift field id; `<field>_default` is the field's Thrift default.
        // Neither is read by AdHoc.
        // Thrift declares no size bounds. These permissive defaults replace AdHoc's 255 limit;
        // add [D(+N)] on a field whose real bound is known.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        // ═════════════════════════ shared.thrift ═════════════════════════

        public class SharedStruct {
            [X] int key; // 1:
            string value; // 2:
        }

        // ───── packs of service SharedService ─────

        /**
        Arguments of SharedService.getStruct().
        */
        public class SharedService_getStruct_Args {
            [X] int key; // 1:
        }

        /**
        Result of SharedService.getStruct().
        */
        public class SharedService_getStruct_Result {
            SharedStruct success; // 0:
        }

        // ═════════════════════════ topology ═════════════════════════

        // Calls the services (Left side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // Implements the services (Right side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface ClientServer : Connects<Client, Server> {

            /**
            Thrift service SharedService
            */
            interface SharedService {
                (L____________, SharedService_getStruct_Result) getStruct(SharedService_getStruct_Args req);
            }
        }

        // ═════════════════════════ Thrift metadata attribute ═════════════════════════

        // Not read by AdHoc; kept so a Thrift annotation survives the conversion.

        /** Thrift annotation `(key = "value")` on the field or its type. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AnnotationAttribute : Attribute { public AnnotationAttribute(string key, string value) { } }
    }
}
