// Generated by Thrift2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: ThriftTest.thrift
// ThriftTest.thrift: namespace c_glib TTest
// ThriftTest.thrift: namespace cpp thrift.test
// ThriftTest.thrift: namespace delphi Thrift.Test
// ThriftTest.thrift: namespace go thrifttest
// ThriftTest.thrift: namespace java thrift.test
// ThriftTest.thrift: namespace js ThriftTest
// ThriftTest.thrift: namespace lua ThriftTest
// ThriftTest.thrift: namespace netstd ThriftTest
// ThriftTest.thrift: namespace perl ThriftTest
// ThriftTest.thrift: namespace php ThriftTest
// ThriftTest.thrift: namespace py ThriftTest
// ThriftTest.thrift: namespace py.twisted ThriftTest
// ThriftTest.thrift: namespace rb Thrift.Test
// ThriftTest.thrift: namespace st ThriftTest
// ThriftTest.thrift: namespace xsd test
// ThriftTest.thrift: namespace noexist ThriftTest
// ThriftTest.thrift: namespace cpp.noexist ThriftTest
// ThriftTest.thrift: namespace * thrift.test
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.thrift {
    /**
        <see cref = 'Bonk'/>
        <see cref = 'BoolTest'/>
        <see cref = 'Bools'/>
        <see cref = 'CrazyNesting'/>
        <see cref = 'EmptyStruct'/>
        <see cref = 'GuessProtocolStruct'/>
        <see cref = 'Insanity'/>
        <see cref = 'LargeDeltas'/>
        <see cref = 'ListBonks'/>
        <see cref = 'ListTypeVersioningV1'/>
        <see cref = 'ListTypeVersioningV2'/>
        <see cref = 'NestedListsBonk'/>
        <see cref = 'NestedListsI32x2'/>
        <see cref = 'NestedListsI32x3'/>
        <see cref = 'NestedMixedx2'/>
        <see cref = 'OneField'/>
        <see cref = 'OptionalBinary'/>
        <see cref = 'OptionalSetDefaultTest'/>
        <see cref = 'SecondService_secondtestString_Args'/>
        <see cref = 'SecondService_secondtestString_Result'/>
        <see cref = 'SomeUnion'/>
        <see cref = 'StructA'/>
        <see cref = 'StructB'/>
        <see cref = 'ThriftTest_testBinary_Args'/>
        <see cref = 'ThriftTest_testBinary_Result'/>
        <see cref = 'ThriftTest_testBool_Args'/>
        <see cref = 'ThriftTest_testBool_Result'/>
        <see cref = 'ThriftTest_testByte_Args'/>
        <see cref = 'ThriftTest_testByte_Result'/>
        <see cref = 'ThriftTest_testDouble_Args'/>
        <see cref = 'ThriftTest_testDouble_Result'/>
        <see cref = 'ThriftTest_testEnum_Args'/>
        <see cref = 'ThriftTest_testEnum_Result'/>
        <see cref = 'ThriftTest_testException_Args'/>
        <see cref = 'ThriftTest_testException_Result'/>
        <see cref = 'ThriftTest_testI32_Args'/>
        <see cref = 'ThriftTest_testI32_Result'/>
        <see cref = 'ThriftTest_testI64_Args'/>
        <see cref = 'ThriftTest_testI64_Result'/>
        <see cref = 'ThriftTest_testInsanity_Args'/>
        <see cref = 'ThriftTest_testInsanity_Result'/>
        <see cref = 'ThriftTest_testList_Args'/>
        <see cref = 'ThriftTest_testList_Result'/>
        <see cref = 'ThriftTest_testMapMap_Args'/>
        <see cref = 'ThriftTest_testMapMap_Result'/>
        <see cref = 'ThriftTest_testMap_Args'/>
        <see cref = 'ThriftTest_testMap_Result'/>
        <see cref = 'ThriftTest_testMultiException_Args'/>
        <see cref = 'ThriftTest_testMultiException_Result'/>
        <see cref = 'ThriftTest_testMulti_Args'/>
        <see cref = 'ThriftTest_testMulti_Result'/>
        <see cref = 'ThriftTest_testNest_Args'/>
        <see cref = 'ThriftTest_testNest_Result'/>
        <see cref = 'ThriftTest_testOneway_Args'/>
        <see cref = 'ThriftTest_testSet_Args'/>
        <see cref = 'ThriftTest_testSet_Result'/>
        <see cref = 'ThriftTest_testStringMap_Args'/>
        <see cref = 'ThriftTest_testStringMap_Result'/>
        <see cref = 'ThriftTest_testString_Args'/>
        <see cref = 'ThriftTest_testString_Result'/>
        <see cref = 'ThriftTest_testStruct_Args'/>
        <see cref = 'ThriftTest_testStruct_Result'/>
        <see cref = 'ThriftTest_testTypedef_Args'/>
        <see cref = 'ThriftTest_testTypedef_Result'/>
        <see cref = 'ThriftTest_testUuid_Args'/>
        <see cref = 'ThriftTest_testUuid_Result'/>
        <see cref = 'ThriftTest_testVoid_Args'/>
        <see cref = 'ThriftTest_testVoid_Result'/>
        <see cref = 'VersioningTestV1'/>
        <see cref = 'VersioningTestV2'/>
        <see cref = 'Wrap_List_List_Bonk'/>
        <see cref = 'Wrap_List_List_i32'/>
        <see cref = 'Wrap_List_Map_Insanity_to_string'/>
        <see cref = 'Wrap_Map_Numberz_to_Insanity'/>
        <see cref = 'Wrap_Map_i32_to_Set_List_Map_Insanity_to_string'/>
        <see cref = 'Wrap_Map_i32_to_i32'/>
        <see cref = 'Wrap_Set_List_Map_Insanity_to_string'/>
        <see cref = 'Wrap_Set_i32'/>
        <see cref = 'Wrap_Set_string'/>
        <see cref = 'Xception'/>
        <see cref = 'Xception2'/>
        <see cref = 'Xtruct'/>
        <see cref = 'Xtruct2'/>
        <see cref = 'Xtruct3'/>
    */
    public interface ThriftTest {
        // A trailing `// N:` on a field is its Thrift field id; `<field>_default` is the field's Thrift default.
        // Neither is read by AdHoc.
        // Thrift declares no size bounds. These permissive defaults replace AdHoc's 255 limit;
        // add [D(+N)] on a field whose real bound is known.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        // ═════════════════════════ ThriftTest.thrift ═════════════════════════

        /** Thrift `const` declarations of ThriftTest.thrift (non-transmittable constants container). */
        public struct Consts {
            public const int myNumberz = 1; // Numberz.ONE
        }

        /**
        the following is expected to fail:
        const Numberz urNumberz = ONE;
        */
        public class UserId { [X] long TYPEDEF; }

        public class MapType { Map<string, Bonk> TYPEDEF; }

        /**
        Docstring!
        */
        enum Numberz {
            ONE = 1,
            TWO = 2,
            THREE = 3,
            FIVE = 5,
            SIX = 6,
            EIGHT = 8,
        }

        public class Bonk {
            string message; // 1:
            [X] int Type; // 2:
        }

        public class Bools {
            bool im_true; // 1:
            bool im_false; // 2:
        }

        public class Xtruct {
            string string_thing; // 1:
            sbyte byte_thing; // 4:
            [X] int i32_thing; // 9:
            [X] long i64_thing; // 11:
        }

        public class Xtruct2 {
            /**
            used to be byte, hence the name
            */
            sbyte byte_thing; // 1:
            Xtruct struct_thing; // 2:
            [X] int i32_thing; // 3:
        }

        public class Xtruct3 {
            string string_thing; // 1:
            [X] int changed; // 4:
            [X] int i32_thing; // 9:
            [X] long i64_thing; // 11:
        }

        /**
        annotation python.immutable = ""
        */
        public class Insanity {
            Map<Numberz, UserId> userMap; // 1:
            Xtruct[,,] xtructs; // 2:
        }

        public class CrazyNesting {
            string string_field; // 1:
            Set<Insanity> set_field; // 2:
            Map<Wrap_Set_i32, Wrap_Map_i32_to_Set_List_Map_Insanity_to_string>[,,] list_field; // 3:
            Binary[,,] binary_field; // 4:
            [D(16)] Binary[] uuid_field; // 5:
        }

        /**
        Thrift union: exactly one of the fields is set.
        */
        public class SomeUnion {
            Map<Numberz, UserId> map_thing; // 1:
            string string_thing; // 2:
            [X] int? i32_thing; // 3:
            Xtruct3 xtruct_thing; // 4:
            Insanity insanity_thing; // 5:
        }

        /**
        Thrift exception.
        */
        public class Xception {
            [X] int errorCode; // 1:
            string message; // 2:
        }

        /**
        Thrift exception.
        */
        public class Xception2 {
            [X] int errorCode; // 1:
            Xtruct struct_thing; // 2:
        }

        public class EmptyStruct {
        }

        public class OneField {
            /**
            Thrift type EmptyStruct is an empty struct: carried as a bool presence flag.
            */
            bool field; // 1:
        }

        public class VersioningTestV1 {
            [X] int begin_in_both; // 1:
            string old_string; // 3:
            [X] int end_in_both; // 12:
        }

        public class VersioningTestV2 {
            [X] int begin_in_both; // 1:
            [X] int newint; // 2:
            sbyte newbyte; // 3:
            [X] short newshort; // 4:
            [X] long newlong; // 5:
            double newdouble; // 6:
            Bonk newstruct; // 7:
            [X] int[,,] newlist; // 8:
            [Key: X] Set<int> newset; // 9:
            [Key: X] [Val: X] Map<int, int> newmap; // 10:
            string newstring; // 11:
            [X] int end_in_both; // 12:
        }

        public class ListTypeVersioningV1 {
            [X] int[,,] myints; // 1:
            string hello; // 2:
        }

        public class ListTypeVersioningV2 {
            string[,,] strings; // 1:
            string hello; // 2:
        }

        public class GuessProtocolStruct {
            Map<string, string> map_field; // 7:
        }

        public class LargeDeltas {
            Bools b1; // 1:
            Bools b10; // 10:
            Bools b100; // 100:
            bool check_true; // 500:
            Bools b1000; // 1000:
            bool check_false; // 1500:
            VersioningTestV2 vertwo2000; // 2000:
            Set<string> a_set2500; // 2500:
            VersioningTestV2 vertwo3000; // 3000:
            [X] int[,,] big_numbers; // 4000:
        }

        public class NestedListsI32x2 {
            int[,,][,,] integerlist; // 1:
        }

        public class NestedListsI32x3 {
            Wrap_List_List_i32[,,] integerlist; // 1:
        }

        public class NestedMixedx2 {
            Set<int>[,,] int_set_list; // 1:
            [Key: X] Map<int, Wrap_Set_string> map_int_strset; // 2:
            Map<int, Wrap_Set_string>[,,] map_int_strset_list; // 3:
        }

        public class ListBonks {
            Bonk[,,] bonk; // 1:
        }

        public class NestedListsBonk {
            Wrap_List_List_Bonk[,,] bonk; // 1:
        }

        public class BoolTest {
            bool? b; // 1:
            public const bool b_default = true;
            string s; // 2:
            public const string s_default = "true";
        }

        public class StructA {
            string s; // 1:
        }

        public class StructB {
            StructA aa; // 1:
            StructA ab; // 2:
        }

        public class OptionalSetDefaultTest {
            Set<string> with_default; // 1:
            public static string[] with_default_default = { "test" };
        }

        public class OptionalBinary {
            Set<Binary[,,]> bin_set; // 1:
            // const bin_set_default = {} — map constant has no C# literal form, skipped
            [Val: X] Map<Binary[,,], int> bin_map; // 2:
            // const bin_map_default = {} — map constant has no C# literal form, skipped
        }

        // ───── packs of service ThriftTest ─────

        /**
        Prints "testVoid()" and returns nothing.
        Arguments of ThriftTest.testVoid().
        */
        public class ThriftTest_testVoid_Args {
        }

        /**
        Result of ThriftTest.testVoid() (void).
        */
        public class ThriftTest_testVoid_Result {
        }

        /**
        Prints 'testString("%s")' with thing as '%s'
        @param string thing - the string to print
        @return string - returns the string 'thing'
        Arguments of ThriftTest.testString().
        */
        public class ThriftTest_testString_Args {
            string thing; // 1:
        }

        /**
        Result of ThriftTest.testString().
        */
        public class ThriftTest_testString_Result {
            string success; // 0:
        }

        /**
        Prints 'testBool("%s")' where '%s' with thing as 'true' or 'false'
        @param bool  thing - the bool data to print
        @return bool  - returns the bool 'thing'
        Arguments of ThriftTest.testBool().
        */
        public class ThriftTest_testBool_Args {
            bool thing; // 1:
        }

        /**
        Result of ThriftTest.testBool().
        */
        public class ThriftTest_testBool_Result {
            bool success; // 0:
        }

        /**
        Prints 'testByte("%d")' with thing as '%d'
        The types i8 and byte are synonyms, use of i8 is encouraged, byte still exists for the sake of compatibility.
        @param byte thing - the i8/byte to print
        @return i8 - returns the i8/byte 'thing'
        Arguments of ThriftTest.testByte().
        */
        public class ThriftTest_testByte_Args {
            sbyte thing; // 1:
        }

        /**
        Result of ThriftTest.testByte().
        */
        public class ThriftTest_testByte_Result {
            sbyte success; // 0:
        }

        /**
        Prints 'testI32("%d")' with thing as '%d'
        @param i32 thing - the i32 to print
        @return i32 - returns the i32 'thing'
        Arguments of ThriftTest.testI32().
        */
        public class ThriftTest_testI32_Args {
            [X] int thing; // 1:
        }

        /**
        Result of ThriftTest.testI32().
        */
        public class ThriftTest_testI32_Result {
            [X] int success; // 0:
        }

        /**
        Prints 'testI64("%d")' with thing as '%d'
        @param i64 thing - the i64 to print
        @return i64 - returns the i64 'thing'
        Arguments of ThriftTest.testI64().
        */
        public class ThriftTest_testI64_Args {
            [X] long thing; // 1:
        }

        /**
        Result of ThriftTest.testI64().
        */
        public class ThriftTest_testI64_Result {
            [X] long success; // 0:
        }

        /**
        Prints 'testDouble("%f")' with thing as '%f'
        @param double thing - the double to print
        @return double - returns the double 'thing'
        Arguments of ThriftTest.testDouble().
        */
        public class ThriftTest_testDouble_Args {
            double thing; // 1:
        }

        /**
        Result of ThriftTest.testDouble().
        */
        public class ThriftTest_testDouble_Result {
            double success; // 0:
        }

        /**
        Prints 'testBinary("%s")' where '%s' is a hex-formatted string of thing's data
        @param binary  thing - the binary data to print
        @return binary  - returns the binary 'thing'
        Arguments of ThriftTest.testBinary().
        */
        public class ThriftTest_testBinary_Args {
            Binary[,,] thing; // 1:
        }

        /**
        Result of ThriftTest.testBinary().
        */
        public class ThriftTest_testBinary_Result {
            Binary[,,] success; // 0:
        }

        /**
        Prints 'testUuid("%s")' where '%s' is the uuid given. Note that the uuid byte order should be correct.
        @param uuid  thing - the uuid to print
        @return uuid  - returns the uuid 'thing'
        Arguments of ThriftTest.testUuid().
        */
        public class ThriftTest_testUuid_Args {
            [D(16)] Binary[] thing; // 1:
        }

        /**
        Result of ThriftTest.testUuid().
        */
        public class ThriftTest_testUuid_Result {
            [D(16)] Binary[] success; // 0:
        }

        /**
        Prints 'testStruct("{%s}")' where thing has been formatted into a string of comma separated values
        @param Xtruct thing - the Xtruct to print
        @return Xtruct - returns the Xtruct 'thing'
        Arguments of ThriftTest.testStruct().
        */
        public class ThriftTest_testStruct_Args {
            Xtruct thing; // 1:
        }

        /**
        Result of ThriftTest.testStruct().
        */
        public class ThriftTest_testStruct_Result {
            Xtruct success; // 0:
        }

        /**
        Prints 'testNest("{%s}")' where thing has been formatted into a string of the nested struct
        @param Xtruct2 thing - the Xtruct2 to print
        @return Xtruct2 - returns the Xtruct2 'thing'
        Arguments of ThriftTest.testNest().
        */
        public class ThriftTest_testNest_Args {
            Xtruct2 thing; // 1:
        }

        /**
        Result of ThriftTest.testNest().
        */
        public class ThriftTest_testNest_Result {
            Xtruct2 success; // 0:
        }

        /**
        Prints 'testMap("{%s")' where thing has been formatted into a string of 'key =&gt; value' pairs
        separated by commas and new lines
        @param map&lt;i32,i32&gt; thing - the map&lt;i32,i32&gt; to print
        @return map&lt;i32,i32&gt; - returns the map&lt;i32,i32&gt; 'thing'
        Arguments of ThriftTest.testMap().
        */
        public class ThriftTest_testMap_Args {
            [Key: X] [Val: X] Map<int, int> thing; // 1:
        }

        /**
        Result of ThriftTest.testMap().
        */
        public class ThriftTest_testMap_Result {
            [Key: X] [Val: X] Map<int, int> success; // 0:
        }

        /**
        Prints 'testStringMap("{%s}")' where thing has been formatted into a string of 'key =&gt; value' pairs
        separated by commas and new lines
        @param map&lt;string,string&gt; thing - the map&lt;string,string&gt; to print
        @return map&lt;string,string&gt; - returns the map&lt;string,string&gt; 'thing'
        Arguments of ThriftTest.testStringMap().
        */
        public class ThriftTest_testStringMap_Args {
            Map<string, string> thing; // 1:
        }

        /**
        Result of ThriftTest.testStringMap().
        */
        public class ThriftTest_testStringMap_Result {
            Map<string, string> success; // 0:
        }

        /**
        Prints 'testSet("{%s}")' where thing has been formatted into a string of values
        separated by commas and new lines
        @param set&lt;i32&gt; thing - the set&lt;i32&gt; to print
        @return set&lt;i32&gt; - returns the set&lt;i32&gt; 'thing'
        Arguments of ThriftTest.testSet().
        */
        public class ThriftTest_testSet_Args {
            [Key: X] Set<int> thing; // 1:
        }

        /**
        Result of ThriftTest.testSet().
        */
        public class ThriftTest_testSet_Result {
            [Key: X] Set<int> success; // 0:
        }

        /**
        Prints 'testList("{%s}")' where thing has been formatted into a string of values
        separated by commas and new lines
        @param list&lt;i32&gt; thing - the list&lt;i32&gt; to print
        @return list&lt;i32&gt; - returns the list&lt;i32&gt; 'thing'
        Arguments of ThriftTest.testList().
        */
        public class ThriftTest_testList_Args {
            [X] int[,,] thing; // 1:
        }

        /**
        Result of ThriftTest.testList().
        */
        public class ThriftTest_testList_Result {
            [X] int[,,] success; // 0:
        }

        /**
        Prints 'testEnum("%d")' where thing has been formatted into its numeric value
        @param Numberz thing - the Numberz to print
        @return Numberz - returns the Numberz 'thing'
        Arguments of ThriftTest.testEnum().
        */
        public class ThriftTest_testEnum_Args {
            Numberz thing; // 1:
        }

        /**
        Result of ThriftTest.testEnum().
        */
        public class ThriftTest_testEnum_Result {
            Numberz success; // 0:
        }

        /**
        Prints 'testTypedef("%d")' with thing as '%d'
        @param UserId thing - the UserId to print
        @return UserId - returns the UserId 'thing'
        Arguments of ThriftTest.testTypedef().
        */
        public class ThriftTest_testTypedef_Args {
            UserId thing; // 1:
        }

        /**
        Result of ThriftTest.testTypedef().
        */
        public class ThriftTest_testTypedef_Result {
            UserId success; // 0:
        }

        /**
        Prints 'testMapMap("%d")' with hello as '%d'
        @param i32 hello - the i32 to print
        @return map&lt;i32,map&lt;i32,i32&gt;&gt; - returns a dictionary with these values:
        {-4 =&gt; {-4 =&gt; -4, -3 =&gt; -3, -2 =&gt; -2, -1 =&gt; -1, }, 4 =&gt; {1 =&gt; 1, 2 =&gt; 2, 3 =&gt; 3, 4
        =&gt; 4, }, }
        Arguments of ThriftTest.testMapMap().
        */
        public class ThriftTest_testMapMap_Args {
            [X] int hello; // 1:
        }

        /**
        Result of ThriftTest.testMapMap().
        */
        public class ThriftTest_testMapMap_Result {
            [Key: X] Map<int, Wrap_Map_i32_to_i32> success; // 0:
        }

        /**
        So you think you've got this all worked out, eh?
        Creates a map with these values and prints it out:
        { 1 =&gt; { 2 =&gt; argument,
        3 =&gt; argument,
        },
        2 =&gt; { 6 =&gt; &lt;empty Insanity struct&gt;, },
        }
        @return map&lt;UserId, map&lt;Numberz,Insanity&gt;&gt; - a map with the above values
        Arguments of ThriftTest.testInsanity().
        */
        public class ThriftTest_testInsanity_Args {
            Insanity argument; // 1:
        }

        /**
        Result of ThriftTest.testInsanity().
        */
        public class ThriftTest_testInsanity_Result {
            Map<UserId, Wrap_Map_Numberz_to_Insanity> success; // 0:
        }

        /**
        Prints 'testMulti()'
        @param i8 arg0 -
        @param i32 arg1 -
        @param i64 arg2 -
        @param map&lt;i16, string&gt; arg3 -
        @param Numberz arg4 -
        @param UserId arg5 -
        @return Xtruct - returns an Xtruct with string_thing = "Hello2, byte_thing = arg0, i32_thing = arg1
        and i64_thing = arg2
        Arguments of ThriftTest.testMulti().
        */
        public class ThriftTest_testMulti_Args {
            sbyte arg0; // 1:
            [X] int arg1; // 2:
            [X] long arg2; // 3:
            [Key: X] Map<short, string> arg3; // 4:
            Numberz arg4; // 5:
            UserId arg5; // 6:
        }

        /**
        Result of ThriftTest.testMulti().
        */
        public class ThriftTest_testMulti_Result {
            Xtruct success; // 0:
        }

        /**
        Print 'testException(%s)' with arg as '%s'
        @param string arg - a string indication what type of exception to throw
        if arg == "Xception" throw Xception with errorCode = 1001 and message = arg
        else if arg == "TException" throw TException
        else do not throw anything
        Arguments of ThriftTest.testException().
        */
        public class ThriftTest_testException_Args {
            string arg; // 1:
        }

        /**
        Result of ThriftTest.testException() (void).
        */
        public class ThriftTest_testException_Result {
        }

        /**
        Print 'testMultiException(%s, %s)' with arg0 as '%s' and arg1 as '%s'
        @param string arg - a string indicating what type of exception to throw
        if arg0 == "Xception" throw Xception with errorCode = 1001 and message = "This is an Xception"
        else if arg0 == "Xception2" throw Xception2 with errorCode = 2002 and struct_thing.string_thing = "This is an
        Xception2"
        else do not throw anything
        @return Xtruct - an Xtruct with string_thing = arg1
        Arguments of ThriftTest.testMultiException().
        */
        public class ThriftTest_testMultiException_Args {
            string arg0; // 1:
            string arg1; // 2:
        }

        /**
        Result of ThriftTest.testMultiException().
        */
        public class ThriftTest_testMultiException_Result {
            Xtruct success; // 0:
        }

        /**
        Print 'testOneway(%d): Sleeping...' with secondsToSleep as '%d'
        sleep 'secondsToSleep'
        Print 'testOneway(%d): done sleeping!' with secondsToSleep as '%d'
        @param i32 secondsToSleep - the number of seconds to sleep
        Arguments of ThriftTest.testOneway().
        */
        public class ThriftTest_testOneway_Args {
            [X] int secondsToSleep; // 1:
        }

        // ───── packs of service SecondService ─────

        /**
        Prints 'testString("%s")' with thing as '%s'
        @param string thing - the string to print
        @return string - returns the string 'thing'
        Arguments of SecondService.secondtestString().
        */
        public class SecondService_secondtestString_Args {
            string thing; // 1:
        }

        /**
        Result of SecondService.secondtestString().
        */
        public class SecondService_secondtestString_Result {
            string success; // 0:
        }

        // ═════════════════════════ wrappers: a Set/Map/uuid nested inside a Set or Map ═════════════════════════

        public class Wrap_Set_i32 { [Key: X] Set<int> value; }
        public class Wrap_List_Map_Insanity_to_string { Map<Insanity, string>[,,] value; }
        public class Wrap_Set_List_Map_Insanity_to_string { Set<Wrap_List_Map_Insanity_to_string> value; }
        public class Wrap_Map_i32_to_Set_List_Map_Insanity_to_string { [Key: X] Map<int, Wrap_Set_List_Map_Insanity_to_string> value; }
        public class Wrap_List_List_i32 { int[,,][,,] value; }
        public class Wrap_Set_string { Set<string> value; }
        public class Wrap_List_List_Bonk { Bonk[,,][,,] value; }
        public class Wrap_Map_i32_to_i32 { [Key: X] [Val: X] Map<int, int> value; }
        public class Wrap_Map_Numberz_to_Insanity { Map<Numberz, Insanity> value; }

        // ═════════════════════════ topology ═════════════════════════

        // Calls the services (Left side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // Implements the services (Right side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface ClientServer : Connects<Client, Server> {

            /**
            Thrift service ThriftTest
            */
            interface ThriftTest {
                (L____________, ThriftTest_testVoid_Result) testVoid(ThriftTest_testVoid_Args req);
                (L____________, ThriftTest_testString_Result) testString(ThriftTest_testString_Args req);
                (L____________, ThriftTest_testBool_Result) testBool(ThriftTest_testBool_Args req);
                (L____________, ThriftTest_testByte_Result) testByte(ThriftTest_testByte_Args req);
                (L____________, ThriftTest_testI32_Result) testI32(ThriftTest_testI32_Args req);
                (L____________, ThriftTest_testI64_Result) testI64(ThriftTest_testI64_Args req);
                (L____________, ThriftTest_testDouble_Result) testDouble(ThriftTest_testDouble_Args req);
                (L____________, ThriftTest_testBinary_Result) testBinary(ThriftTest_testBinary_Args req);
                (L____________, ThriftTest_testUuid_Result) testUuid(ThriftTest_testUuid_Args req);
                (L____________, ThriftTest_testStruct_Result) testStruct(ThriftTest_testStruct_Args req);
                (L____________, ThriftTest_testNest_Result) testNest(ThriftTest_testNest_Args req);
                (L____________, ThriftTest_testMap_Result) testMap(ThriftTest_testMap_Args req);
                (L____________, ThriftTest_testStringMap_Result) testStringMap(ThriftTest_testStringMap_Args req);
                (L____________, ThriftTest_testSet_Result) testSet(ThriftTest_testSet_Args req);
                (L____________, ThriftTest_testList_Result) testList(ThriftTest_testList_Args req);
                (L____________, ThriftTest_testEnum_Result) testEnum(ThriftTest_testEnum_Args req);
                (L____________, ThriftTest_testTypedef_Result) testTypedef(ThriftTest_testTypedef_Args req);
                (L____________, ThriftTest_testMapMap_Result) testMapMap(ThriftTest_testMapMap_Args req);
                (L____________, ThriftTest_testInsanity_Result) testInsanity(ThriftTest_testInsanity_Args req);
                (L____________, ThriftTest_testMulti_Result) testMulti(ThriftTest_testMulti_Args req);
                (L____________, ThriftTest_testException_Result, Xception) testException(ThriftTest_testException_Args req);
                (L____________, ThriftTest_testMultiException_Result, Xception, Xception2) testMultiException(ThriftTest_testMultiException_Args req);
                // oneway testOneway(): see state ThriftTest_testOneway of the connection
            }

            /**
            Thrift service SecondService
            */
            interface SecondService {
                (L____________, SecondService_secondtestString_Result) secondtestString(SecondService_secondtestString_Args req);
            }

            // oneway methods: fire-and-forget states of the connection's default actor
            [l____________<ThriftTest_testOneway_Args>]
            struct ThriftTest_testOneway { }
        }

        // ═════════════════════════ Thrift metadata attribute ═════════════════════════

        // Not read by AdHoc; kept so a Thrift annotation survives the conversion.

        /** Thrift annotation `(key = "value")` on the field or its type. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AnnotationAttribute : Attribute { public AnnotationAttribute(string key, string value) { } }
    }
}
