// Generated by Thrift2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: shared.thrift, tutorial.thrift
// shared.thrift: namespace cl shared
// shared.thrift: namespace cpp shared
// shared.thrift: namespace d share
// shared.thrift: namespace dart shared
// shared.thrift: namespace java shared
// shared.thrift: namespace perl shared
// shared.thrift: namespace php shared
// shared.thrift: namespace haxe shared
// shared.thrift: namespace netstd shared
// tutorial.thrift: namespace cl tutorial
// tutorial.thrift: namespace cpp tutorial
// tutorial.thrift: namespace d tutorial
// tutorial.thrift: namespace dart tutorial
// tutorial.thrift: namespace java tutorial
// tutorial.thrift: namespace php tutorial
// tutorial.thrift: namespace perl tutorial
// tutorial.thrift: namespace haxe tutorial
// tutorial.thrift: namespace netstd tutorial
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.thrift {
    /**
        <see cref = 'Calculator_add_Args'/>
        <see cref = 'Calculator_add_Result'/>
        <see cref = 'Calculator_calculate_Args'/>
        <see cref = 'Calculator_calculate_Result'/>
        <see cref = 'Calculator_ping_Args'/>
        <see cref = 'Calculator_ping_Result'/>
        <see cref = 'Calculator_zip_Args'/>
        <see cref = 'InvalidOperation'/>
        <see cref = 'Work'/>
        <see cref = 'shared.SharedService_getStruct_Args'/>
        <see cref = 'shared.SharedService_getStruct_Result'/>
        <see cref = 'shared.SharedStruct'/>
    */
    public interface tutorial {
        // A trailing `// N:` on a field is its Thrift field id; `<field>_default` is the field's Thrift default.
        // Neither is read by AdHoc.
        // Thrift declares no size bounds. These permissive defaults replace AdHoc's 255 limit;
        // add [D(+N)] on a field whose real bound is known.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        // ═════════════════════════ include "shared.thrift" ═════════════════════════
        public struct shared {

            public class SharedStruct {
                [X] int key; // 1:
                string value; // 2:
            }

            // ───── packs of service SharedService ─────

            /**
            Arguments of SharedService.getStruct().
            */
            public class SharedService_getStruct_Args {
                [X] int key; // 1:
            }

            /**
            Result of SharedService.getStruct().
            */
            public class SharedService_getStruct_Result {
                shared.SharedStruct success; // 0:
            }
        }

        // ═════════════════════════ tutorial.thrift ═════════════════════════

        /** Thrift `const` declarations of tutorial.thrift (non-transmittable constants container). */
        public struct Consts {
            /**
            Thrift also lets you define constants for use across languages. Complex
            types and structs are specified using JSON notation.
            */
            public const int INT32CONSTANT = 9853;
            // const MAPCONSTANT = {"hello": "world", "goodnight": "moon"} — map constant has no C# literal form, skipped
        }

        /**
        Thrift lets you do typedefs to get pretty names for your types. Standard
        C style here.
        */
        public class MyInteger { [X] int TYPEDEF; }

        /**
        You can define enums, which are just 32 bit integers. Values are optional
        and start at 1 if not supplied, C style again.
        */
        enum Operation {
            ADD = 1,
            SUBTRACT = 2,
            MULTIPLY = 3,
            DIVIDE = 4,
        }

        /**
        Structs are the basic complex data structures. They are comprised of fields
        which each have an integer identifier, a type, a symbolic name, and an
        optional default value.
        Fields can be declared "optional", which ensures they will not be included
        in the serialized output if they aren't set.  Note that this requires some
        manual management in some languages.
        */
        public class Work {
            [X] int num1; // 1:
            public const int num1_default = 0;
            [X] int num2; // 2:
            Operation op; // 3:
            string comment; // 4:
        }

        /**
        Structs can also be exceptions, if they are nasty.
        Thrift exception.
        */
        public class InvalidOperation {
            [X] int whatOp; // 1:
            string why; // 2:
        }

        // ───── packs of service Calculator extends shared.SharedService ─────

        /**
        A method definition looks like C code. It has a return type, arguments,
        and optionally a list of exceptions that it may throw. Note that argument
        lists and exception lists are specified using the exact same syntax as
        field lists in struct or exception definitions.
        Arguments of Calculator.ping().
        */
        public class Calculator_ping_Args {
        }

        /**
        Result of Calculator.ping() (void).
        */
        public class Calculator_ping_Result {
        }

        /**
        Arguments of Calculator.add().
        */
        public class Calculator_add_Args {
            [X] int num1; // 1:
            [X] int num2; // 2:
        }

        /**
        Result of Calculator.add().
        */
        public class Calculator_add_Result {
            [X] int success; // 0:
        }

        /**
        Arguments of Calculator.calculate().
        */
        public class Calculator_calculate_Args {
            [X] int logid; // 1:
            Work w; // 2:
        }

        /**
        Result of Calculator.calculate().
        */
        public class Calculator_calculate_Result {
            [X] int success; // 0:
        }

        /**
        This method has a oneway modifier. That means the client only makes
        a request and does not listen for any response at all. Oneway methods
        must be void.
        Arguments of Calculator.zip().
        */
        public class Calculator_zip_Args {
        }

        // ═════════════════════════ topology ═════════════════════════

        // Calls the services (Left side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // Implements the services (Right side).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface ClientServer : Connects<Client, Server> {

            /**
            Thrift service SharedService
            */
            interface SharedService {
                (L____________, shared.SharedService_getStruct_Result) getStruct(shared.SharedService_getStruct_Args req);
            }

            /**
            Thrift service Calculator
            Ahh, now onto the cool part, defining a service. Services just need a name
            and can optionally inherit from another service using the extends keyword.
            extends shared.SharedService: its methods are declared below as well.
            */
            interface Calculator {
                (L____________, Calculator_ping_Result) ping(Calculator_ping_Args req);
                (L____________, Calculator_add_Result) add(Calculator_add_Args req);
                (L____________, Calculator_calculate_Result, InvalidOperation) calculate(Calculator_calculate_Args req);
                // oneway zip(): see state Calculator_zip of the connection
                // inherited from shared.SharedService
                (L____________, shared.SharedService_getStruct_Result) getStruct(shared.SharedService_getStruct_Args req);
            }

            // oneway methods: fire-and-forget states of the connection's default actor
            [l____________<Calculator_zip_Args>]
            struct Calculator_zip { }
        }

        // ═════════════════════════ Thrift metadata attribute ═════════════════════════

        // Not read by AdHoc; kept so a Thrift annotation survives the conversion.

        /** Thrift annotation `(key = "value")` on the field or its type. */
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class AnnotationAttribute : Attribute { public AnnotationAttribute(string key, string value) { } }
    }
}
